### ISSUE TITLE
which `nose` is required to run `caimanmanager.py test`

### ISSUE THREAD

**Issue by kushalkolar** [flatironinstitute/CaImAn#1021]
This is missing from the contributing docs, https://github.com/flatironinstitute/CaImAn/blob/master/CONTRIBUTING.md 

running `python ./caimanmanager.py test` in the root dir with a symlink install, i.e. `pip install -e .`
with only `nose` installed I get

```python3
Traceback (most recent call last):
  File "/home/kushalk/python-venvs/mescore/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/usr/local/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/usr/local/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/local/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/loader.py", line 354, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/loader.py", line 191, in loadTestsFromDir
    yield self.loadTestsFromName(
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/loader.py", line 359, in loadTestsFromModule
    return self.suiteClass(ContextList(tests, context=module))
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/suite.py", line 428, in __call__
    return self.makeSuite(tests, context, **kw)
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/suite.py", line 475, in makeSuite
    suite = self.suiteClass(
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/suite.py", line 159, in __init__
    super(ContextSuite, self).__init__(tests)
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/usr/local/lib/python3.10/unittest/suite.py", line 22, in __init__
    self._tests = []
  File "/home/kushalk/python-venvs/mescore/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
Error in runcmd
STDOUT: None
STDERR: None
```

running `python ./caimanmanager.py test` in the root dir with a symlink install, i.e. `pip install -e .`
with only `nose2` installed I get:

```python3
runcmd[nosetests --verbose --traverse-namespace caiman]
Traceback (most recent call last):
  File "/home/kushalk/repos/CaImAn/./caimanmanager.py", line 276, in <module>
    main()
  File "/home/kushalk/repos/CaImAn/./caimanmanager.py", line 238, in main
    do_run_nosetests(cfg.userdir)
  File "/home/kushalk/repos/CaImAn/./caimanmanager.py", line 109, in do_run_nosetests
    out, err, ret = runcmd(["nosetests", "--verbose", "--traverse-namespace", "caiman"])
  File "/home/kushalk/repos/CaImAn/./caimanmanager.py", line 219, in runcmd
    pipeline = subprocess.Popen(cmdlist, stdout=sys.stdout, stderr=sys.stdout)
  File "/usr/local/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'nosetests'
```

But if I have both `nose` and `nose2` installed, and then run `nose2` in the root dir it seems to run successfully?

```
.....
----------------------------------------------------------------------
Ran 15 tests in 61.301s

OK
```

**Comment by GUO-neuroLAB** [comment]
Hi ,i encounter the same condition and i cannot find caimannager.py file in the script folder and cannot find caimannager in my computer. i use the manba to install the caiman. i am in China, is it the net problem?

**Comment by EricThomson** [comment]
@pgunn do you know the answer to this?

**Comment by pgunn** [comment]
The tests were written for v1 of nose.
