### ISSUE TITLE
`numpy.int` deprecation has expired and now throws an error 

### ISSUE THREAD

**Issue by kushalkolar** [flatironinstitute/CaImAn#1024]
Just got this on my CI, it'll give problems to anyone creating new envs so you probably want to patch this rather soon on `master`? numpy releasing large breaking changes right before the holidays :man_shrugging: 

From the release notes:

https://github.com/numpy/numpy/releases
```
The deprecation for the aliases np.object, np.bool, np.float,
np.complex, np.str, and np.int is expired (introduces NumPy
1.20). Some of these will now give a FutureWarning in addition to
raising an error since they will be mapped to the NumPy scalars in
the future.
```

```python3
Traceback (most recent call last):
  File "/usr/share/miniconda/bin/caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
  File "/usr/share/miniconda/lib/python3.9/site-packages/caiman/__init__.py", line 4, in <module>
    from .base.movies import movie, load, load_movie_chain, _load_behavior
  File "/usr/share/miniconda/lib/python3.9/site-packages/caiman/base/movies.py", line 59, in <module>
    from ..utils import visualization
  File "/usr/share/miniconda/lib/python3.9/site-packages/caiman/utils/visualization.py", line 37, in <module>
    from ..summary_images import local_correlations
  File "/usr/share/miniconda/lib/python3.9/site-packages/caiman/summary_images.py", line 23, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
  File "/usr/share/miniconda/lib/python3.9/site-packages/caiman/source_extraction/cnmf/__init__.py", line 3, in <module>
    from . import utilities
  File "/usr/share/miniconda/lib/python3.9/site-packages/caiman/source_extraction/cnmf/utilities.py", line 41, in <module>
    from .initialization import greedyROI
  File "/usr/share/miniconda/lib/python3.9/site-packages/caiman/source_extraction/cnmf/initialization.py", line 43, in <module>
    from .spatial import circular_constraint, connectivity_constraint
  File "/usr/share/miniconda/lib/python3.9/site-packages/caiman/source_extraction/cnmf/spatial.py", line 56, in <module>
    se=np.ones((3, 3), dtype=np.int),
  File "/usr/share/miniconda/lib/python3.9/site-packages/numpy/__init__.py", line 284, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'int'
```

**Comment by vkonan** [comment]
^Bump

Yep I'm getting this error too. 

Glad it's not just me. I was banging my head against the wall and saw your post. Thanks for refreshing my sanity.
