### ISSUE TITLE
unresponsive cells in demo_pipeline_cnmfE

### ISSUE THREAD

**Issue by dprotter** [flatironinstitute/CaImAn#1049]
Please fill in the following for any issues

Your setup:
 1. Operating System (Linux, MacOS, Windows): Ubuntu 20.04
 2. Hardware type (x86, ARM..) and RAM: x86, 128 GB RAM
 3. Python Version (e.g. 3.9): 3.10.9
 4. Caiman version (e.g. 1.9.12): 1.9.13
 5. Which demo exhibits the problem (if applicable): demo_pipeline_cnmfE
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): pure conda + ipykernel install for jupyter
 8. Details: 
 
I'm getting a strange behavior I've never had before in ipynotebooks: cells wont run/will hang while running without any output. Even very simple cells like
`print('hi!')`
will hang indefinitely. It seems to be related to the cluster, as things only tend to get wonky after starting that up. Sometimes cells eventually run, and sometimes the kernel just crashes. 

It seems that hitting "kernel interrupt" often actually allows a cell to continue and run. 

I'm assuming this is some threading issue, but neither the notebook nor the jupyter server log seems to give any helpful information. 

Below is an error that popped into the cluster cell when I interrupted the kernel on a data saving step on the demo data after 5-10 minutes. 

Thanks for the help!

`bord_px = 0 if border_nan == 'copy' else bord_px
fname_new = cm.save_memmap(fname_mc, base_name='memmap_', order='C',
                           border_to_0=bord_px)`
>>kernel interrupt<<

` 484830 [motion_correction.py:tile_and_correct_wrapper():3103] [145807] 60
      484830 [motion_correction.py:tile_and_correct_wrapper():3103] [145805] 80
      484832 [motion_correction.py:tile_and_correct_wrapper():3103] [145810] 80
      484834 [motion_correction.py:tile_and_correct_wrapper():3103] [145799] 80
      484838 [motion_correction.py:tile_and_correct_wrapper():3103] [145804] 80
      484843 [motion_correction.py:tile_and_correct_wrapper():3103] [145808] 70
      484844 [motion_correction.py:tile_and_correct_wrapper():3103] [145802] 60
      484852 [motion_correction.py:tile_and_correct_wrapper():3103] [145803] 60
      484857 [motion_correction.py:tile_and_correct_wrapper():3103] [145807] 70
      484870 [motion_correction.py:tile_and_correct_wrapper():3103] [145808] 80
      484871 [motion_correction.py:tile_and_correct_wrapper():3103] [145802] 70
      484879 [motion_correction.py:tile_and_correct_wrapper():3103] [145803] 70
      484886 [motion_correction.py:tile_and_correct_wrapper():3103] [145807] 80
      484897 [motion_correction.py:tile_and_correct_wrapper():3103] [145802] 80
      484905 [motion_correction.py:tile_and_correct_wrapper():3103] [145803] 80
Process ForkPoolWorker-10:
Process ForkPoolWorker-8:
Process ForkPoolWorker-13:
Process ForkPoolWorker-19:
Process ForkPoolWorker-15:
Process ForkPoolWorker-21:
Process ForkPoolWorker-20:
Process ForkPoolWorker-3:
Process ForkPoolWorker-23:
Process ForkPoolWorker-6:
Process ForkPoolWorker-12:
Process ForkPoolWorker-9:
Process ForkPoolWorker-11:
Process ForkPoolWorker-17:
Process ForkPoolWorker-2:
Process ForkPoolWorker-16:
Process ForkPoolWorker-1:
Process ForkPoolWorker-18:
Process ForkPoolWorker-22:
Process ForkPoolWorker-14:
Process ForkPoolWorker-5:
Process ForkPoolWorker-7:
Process ForkPoolWorker-4:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 365, in get
    res = self._reader.recv_bytes()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/queues.py", line 364, in get
    with self._rlock:
KeyboardInterrupt
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
KeyboardInterrupt
KeyboardInterrupt
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
KeyboardInterrupt
KeyboardInterrupt
KeyboardInterrupt
  File "/home/dprotter/anaconda3/envs/caiman/lib/python3.10/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt`

**Comment by pgunn** [comment]
Hello,
Is this a fresh install of caiman on a system where it worked okay before? Same data? Demo data or your own?

How much RAM does the system have? Are there any indications that it's running low while Caiman is running?

**Comment by dprotter** [comment]
Fresh conda install yesterday. I've had a few different packages installed that relied on caiman for its CNMF-E implementation, but havent tried running the actual caiman notebooks before.

128GB of RAM. plenty left. Often very little CPU use while hanging. 

Happens with both caiman demo data and my own data.

I should also mention I had some issues with tornado/zmq in both this env and another env, but that seemed to be fixed by downgrading jupyter-client==7.3.2 and tornado==6.1 ([see this issue](https://discourse.jupyter.org/t/jupyter-notebook-zmq-message-arrived-on-closed-channel-error/17869)). Issue with hanging also  occurred before this downgrade. 

thanks!

**Comment by pgunn** [comment]
Right now I don't have a theory as to whether this is a general Jupyter issue or an issue with Caiman. There are two routes we can go to try to figure out which (you might try both):

1) Try to find and run some reasonably complex Jupyter notebooks unrelated to caiman. You might be able to find some demo stuff that uses numpy or something like that. See if the same behaviour turns up.
2) If you're comfortable with it, try using the commandline demos of caiman; ideally pick one as similar to the notebook you care about and see how it behaves

**Comment by dprotter** [comment]
alright, sounds good. thanks for the thoughts!

If I figure anything out I'll update you.

**Comment by j-friedrich** [comment]
I had the same issue. Apparently the qt backend is to blame, you can just comment out or delete the 4th line in the 1st cell: `get_ipython().magic(u'matplotlib qt')`. I updated the demo in the dev branch.
