### ISSUE TITLE
Cannot set up caimanmanager

### ISSUE THREAD

**Issue by cyberfag** [flatironinstitute/CaImAn#1050]
Windows x64, 64 GB RAM, primary Python is Anacona's 3.9.12 (added to PATH during installation), Caiman version 1.9.13

I'm trying to install Caiman in the package-based way. Mamba and then Caiman installed successfully. But when it comes to caimanmanager I use the recommended command `caimanmanager.py install` it gives me the following error:

> Traceback (most recent call last):
  File "C:\Users\Sykesva\anaconda3\envs\caiman\bin\caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\caiman\__init__.py", line 3, in <module>
    import pkg_resources
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pkg_resources\__init__.py", line 82, in <module>
    from pkg_resources.extern import platformdirs
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pkg_resources\extern\__init__.py", line 44, in load_module
    raise ImportError(
ImportError: The 'platformdirs' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

When I use the alternative command mentioned in the installation guide `pip install .` it gives another error: 

> Traceback (most recent call last):
  File "C:\Users\Sykesva\anaconda3\envs\caiman\Scripts\pip-script.py", line 5, in <module>
    from pip._internal.cli.main import main
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\cli\main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\utils\misc.py", line 43, in <module>
    from pip._internal.locations import get_major_minor_version
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 44, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 23, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\site-packages\pip\_vendor\platformdirs\windows.py", line 3, in <module>
    import ctypes
  File "C:\Users\Sykesva\anaconda3\envs\caiman\lib\ctypes\__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.

What's possibly wrong?

**Comment by j-friedrich** [comment]
Seems to duplicate #1046.
platformdirs became a requirement of jupyter-core since version 5.
I don't run into that issue on Linux or Mac, thus probably a Windows issue

**Comment by kushalkolar** [comment]
This user seemed to have got it working after a similar issue https://github.com/flatironinstitute/CaImAn/issues/1044

**Comment by EricThomson** [comment]
@cyberfag have you gotten this sorted?

**Comment by pgunn** [comment]
Closing due to inactivity; please reopen if this is still an issue

**Comment by cyberfag** [comment]
> @cyberfag have you gotten this sorted?

Oh, sorry, I missed all the notifications from this thread. 
Well, eventually, I managed to successfully install CaImAn only by downgrading to older versions which I easily installed on another laptop 1.5 years ago, namely, Anaconda 3.9.7, Mamba 1.3.1, and default CaImAn version (cannot check right now), i.e. I didn't specify it while installing
