### ISSUE TITLE
Tracking task: Build issue in conda-forge on OSX/Intel

### ISSUE THREAD

**Issue by pgunn** [flatironinstitute/CaImAn#1090]
(this is an internal tracking task, to document and take notes on work)

An August-2023 commit from Johannes added test_motion_correction.py, which tests the motion correction pipeline against known results. Unfortunately, one of the tests seems to fail inside the conda-forge package pipeline (which runs tests to ensure a build is good). The error looks like this in their build system:

```
======================================================================
FAIL: caiman.tests.test_motion_correction.test_register_n_apply
----------------------------------------------------------------------
Traceback (most recent call last):
  File "$PREFIX/lib/python3.10/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "$PREFIX/lib/python3.10/site-packages/caiman/tests/test_motion_correction.py", line 41, in test_register_n_apply
    _test_register_n_apply(2)
  File "$PREFIX/lib/python3.10/site-packages/caiman/tests/test_motion_correction.py", line 37, in _test_register_n_apply
    npt.assert_allclose(frame_cor[~nans], templ[~nans], 1e-6)
  File "$PREFIX/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 1592, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "$PREFIX/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "$PREFIX/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 862, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-06, atol=0

Mismatched elements: 1 / 224 (0.446%)
Max absolute difference: 1.71398234e-07
Max relative difference: 1.05664514e-06
 x: array([0.792157, 0.845752, 0.900654, 0.913726, 0.921569, 0.930719,
       0.942484, 0.934641, 0.933334, 0.934641, 0.920262, 0.900654,
       0.878431, 0.818301, 0.620915, 0.509804, 0.72549 , 0.759477,...
 y: array([0.792157, 0.845752, 0.900654, 0.913725, 0.921569, 0.930719,
       0.942484, 0.934641, 0.933333, 0.934641, 0.920261, 0.900654,
       0.878431, 0.818301, 0.620915, 0.509804, 0.72549 , 0.759477,...
```

This tracking task is to understand the problem and find a fix, ideally before the next time we cut a release of Caiman.

**Comment by pgunn** [comment]
On an OSX/Intel Mac I have at home, I did a source build of caiman from the dev branch and did not see the error:

```
(caiman) pgunn@verthanti caiman_data % nosetests --verbose ~/miniconda3/envs/caiman/lib/python3.10/site-packages/caiman/tests/test_motion_correction.py:test_register_n_apply
2023-05-21 21:59:03.543422: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
caiman.tests.test_motion_correction.test_register_n_apply ... ok

----------------------------------------------------------------------
Ran 1 test in 0.005s

OK
```

On the theory that the new "DNN" optimisations in Tensorflow are related, I tried with TF_ENABLE_ONEDNN_OPTS set to 0, 1, or unset and got the same OK each time. On the chance that the tensorflow version is relevant, the environment on my home Mac ended up with version 2.11.1.

**Comment by pgunn** [comment]
The version of tensorflow in the build environment on conda-forge exactly matches (down to the build id) the version on my test Mac.

**Comment by pgunn** [comment]
Ah, apparently Johannes actually fixed this in dev after the last release and I didn't notice. So the next release should be fine. Closing this issue.
