### ISSUE TITLE
`caimanmanager.py` requires conda

### ISSUE THREAD

**Issue by loftusa** [flatironinstitute/CaImAn#1111]
I am not using anaconda with caiman because I am working in isolated docker containers.

`(base) jovyan@phanes-calciumexp-alex-deploy-5864594868-dtmps:~/work/pipelines/CaImAn$ python caimanmanager.py install` on the command line returns

```
2023-06-13 00:16:25.459585: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/home/jovyan/work/pipelines/CaImAn/caimanmanager.py", line 276, in <module>
    main()
  File "/home/jovyan/work/pipelines/CaImAn/caimanmanager.py", line 234, in main
    do_install_to(cfg.userdir, cfg.inplace, cfg.force)
  File "/home/jovyan/work/pipelines/CaImAn/caimanmanager.py", line 60, in do_install_to
    shutil.copytree(sourcedir_base, targdir)
  File "/opt/conda/lib/python3.10/shutil.py", line 556, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/conda/share/caiman'
```

It should be possible to install this without being in a conda environment.

**Comment by loftusa** [comment]
Update: Solved this, requires `--inplace` flag

**Comment by EricThomson** [comment]
Closing because looks solved: note the next release (coming this week most likely) will have fairly major changes to caimanmanager usage, and docs on installation, so keep an eye open for that as you may need to change your Dockerfile.

**Comment by pgunn** [comment]
Hello,
I don't think this is a result of a conda dependency; it's rather that some unorthodox install method for caiman was used (or an odd value for CAIMAN_DATA is being used, or similar). I doubt the changes coming next week will actually address this.

If `--inplace` works for you, great, but I am curious what led to it being necessary (unless it really was just `pip install -e .` in which case it's not surprising at all).

**Comment by EricThomson** [comment]
I was assuming dev install: @loftusa  if this is wrong, feel free to reopen issue.
