### ISSUE TITLE
Error when the input tif file consisting of 3D images

### ISSUE THREAD

**Issue by Anti-Involution** [flatironinstitute/CaImAn#1231]
Your setup:
 1. Operating System (Linux, MacOS, Windows): MacOS
 2. Hardware type (x86, ARM..) and RAM: x86
 3. Python Version (e.g. 3.9): 3.9
 4. Caiman version (e.g. 1.9.12): 1.9.16
 5. Which demo exhibits the problem (if applicable):
 6. How you installed Caiman (pure conda, conda + compile, colab, ..): pure pip
 7. Details: 
When my input is a tif file which consists of 160 images(size: 512\*512\*3), I got the following error:

```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mesmerize_core/algorithms/mcorr.py", line 67, in run_algo
    mc.motion_correct(save_movie=True)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/caiman/motion_correction.py", line 242, in motion_correct
    mi = min(mi, next(iterator).min()[()])
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/caiman/base/movies.py", line 2160, in load_iter
    vol[i] = y.asarray()
ValueError: could not broadcast input array from shape (512,512,3) into shape (512,3)
```

**Comment by Anti-Involution** [comment]
Anyone meets this problem?
