### ISSUE TITLE
new sbx tests have issues on windows

### ISSUE THREAD

**Issue by pgunn** [flatironinstitute/CaImAn#1319]
The new SBX tests don't work in CI on Windows due to file locking; for now to get a working release I'm going to disable them (only on Windows) in caimanmanager, but I need to get back to this and figure out why this is happening.

I suspect because of the way the tests are invoked (as part of a single big process rather than separate processes for each tests), the solution will likely be to delete intermediate objects that are holding the file open; if I'm write the sbx tests are literally stepping on each others feet.

Another option would be to have them use distinctly named temporary files.

The issues look like this:
```
ERROR: caiman.tests.test_sbx.test_sbx_to_tif
--------------------------ERROR: caiman.tests.test_sbx.test_sbx_to_tif
----------------------------------------------------------------------
Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "%PREFIX%\lib\site-packages\caiman\tests\test_sbx.py", line 133, in test_sbx_to_tif
    os.remove(tif_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\VssAdministrator\\caiman_data\\temp\\from_sbx.tif'
--------------------------------------------
Traceback (most recent call last):
  File "%PREFIX%\lib\site-packages\nose\case.py", line 197, in runTest
    self.test(*self.arg)
  File "%PREFIX%\lib\site-packages\caiman\tests\test_sbx.py", line 133, in test_sbx_to_tif
    os.remove(tif_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\VssAdministrator\\caiman_data\\temp\\from_sbx.tif'
```

(and so on with chain_to_tiff)

**Comment by pgunn** [comment]
May for now it's simpler to not have it clean up after itself; special-casing the nosetests is proving to be more trouble than its worth.

**Comment by pgunn** [comment]
Adjusted the sbx test code to use distinct filenames for each step and not to clean them up. Also adjusted try/except block. If this works and we get a smooth release I will close this ticket.

**Comment by pgunn** [comment]
Now test_sbx_chain_to_tif is failing, but only on Windows. Other sbx tests succeed, and on other platforms this test is not causing a problem.

**Comment by pgunn** [comment]
Reminder: remove intermediate releases once we have things sorted out and have a release going out on conda-forge

**Comment by pgunn** [comment]
Hopefully fixed with 1.10.9, which removed a flag to tifffile.imwrite that doesn't seem to be reliably present, depending on tifffile version. Windows was a red herring; the actual issue was different tifffile versions being delivered as part of the environment. The mode flag defaults to what the test was specifying anyhow.

If this gives us a good package build matrix, we can close this ticket; I had intended to do smaller quick fixes but ended up fixing things the right way.

**Comment by pgunn** [comment]
And by 1.10.9 I really mean 1.10.8 but had a brain goof because of the post-release version bump I just did.

**Comment by pgunn** [comment]
Worked through this, found and fixed a few other minor issues along the way. Release is finally out, and I'm fairly happy with where the test is now.
