### ISSUE TITLE
The error "TypeError: init() got an unexpected keyword argument 'normalize'" occurred in the line "cnm2 = cnm.refit(images, dview=dview)" in the demo_pipeline.

### ISSUE THREAD

**Issue by lsookie** [flatironinstitute/CaImAn#1333]
The error "TypeError: init() got an unexpected keyword argument 'normalize'" occurred in the line "cnm2 = cnm.refit(images, dview=dview)" in the demo_pipeline.
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\souky\caiman_data\demos\general\demo_pipeline.py", line 220, in main
    cnm2 = cnm.refit(images, dview=dview)
  File "D:\Anaconda\envs\ca1\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 419, in refit
    return cnm.fit(images)
  File "D:\Anaconda\envs\ca1\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 537, in fit
    self.update_spatial(Yr, use_init=True)
  File "D:\Anaconda\envs\ca1\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py", line 929, in update_spatial
    update_spatial_components(Y, C=self.estimates.C, f=self.estimates.f, A_in=self.estimates.A,
  File "D:\Anaconda\envs\ca1\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\spatial.py", line 232, in update_spatial_components
    parallel_result = dview.map_async(
  File "D:\Anaconda\envs\ca1\envs\caiman\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
TypeError: __init__() got an unexpected keyword argument 'normalize'
python-BaseException

**Comment by pgunn** [comment]
Thanks, I'm looking into it. Do you mind telling me what version of caiman you're on?
The output of `conda list caiman` would do.

FYI: I'm currently working on a patch that replaces the CLI demos with significantly reworked versions.

**Comment by lsookie** [comment]
> Thanks, I'm looking into it. Do you mind telling me what version of caiman you're on? The output of `conda list caiman` would do.
> 
> FYI: I'm currently working on a patch that replaces the CLI demos with significantly reworked versions.

The version of Caiman is 1.9.12.
Thank you for your reply, my problem has been solved, it was the scikit-learn version update that caused the problem.

**Comment by pgunn** [comment]
I'm glad it worked out. Cheers
