### ISSUE TITLE
linux run result file not readable in windows gui

### ISSUE THREAD

**Issue by lsookie** [flatironinstitute/CaImAn#1360]
I don't know why it runs extra slow on windows (i9, 32g; RTX1060), not sure if it's the configuration.
Then I tried to run it on another computer and it was slightly faster (linux, 3090), but the results of the run I got an error when I viewed it on windows using the gui.

E:\fangjie\calcuim_image\calman\caiman_gui.py:32: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  get_ipython().magic('load_ext autoreload')
E:\fangjie\calcuim_image\calman\caiman_gui.py:33: DeprecationWarning: `magic(...)` is deprecated since IPython 0.13 (warning added in 8.1), use run_line_magic(magic_name, parameter_s).
  get_ipython().magic('autoreload 2')
Traceback (most recent call last):
  File "D:\anaconda\envs\ca1\envs\caiman\lib\site-packages\IPython\core\interactiveshell.py", line 3550, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-70bb6bc461b0>", line 1, in <module>
    runfile('E:\\fangjie\\calcuim_image\\calman\\caiman_gui.py', wdir='E:\\fangjie\\calcuim_image\\calman')
  File "D:\PyCharm 2024.1.2\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\PyCharm 2024.1.2\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\fangjie\calcuim_image\calman\caiman_gui.py", line 73, in <module>
    mov = caiman.load(cnm_obj.mmap_file)
  File "D:\anaconda\envs\ca1\envs\caiman\lib\site-packages\caiman\base\movies.py", line 1701, in load
    Yr, dims, T = load_memmap(
  File "D:\anaconda\envs\ca1\envs\caiman\lib\site-packages\caiman\mmapping.py", line 59, in load_memmap
    d1, d2, d3, T, order = int(fpart[-9]), int(fpart[-7]), int(fpart[-5]), int(fpart[-1]), fpart[-3]
ValueError: invalid literal for int() with base 10: 'd1'

**Comment by pgunn** [comment]
I'm reminded how ugly (and fragile-looking) that filename-parsing logic is; eventually we'll want to get away from encoding parameters like that in the filename and store them in json or something like that.

I haven't used the caiman_gui.py program for a long time (generally the jupyter notebooks are a better choice for visualisation). I'm guessing the file/path changes a few releases back broke this because I forgot to make corresponding changes to the gui. I'll look at this early next week; I suspect the fix won't be too hard. Sorry for the fuss.

**Comment by pgunn** [comment]
Also, what are the filenames of the hdf5 and mmap files you're trying to load?

**Comment by lsookie** [comment]
I apologize for not getting back to you until now.
      The code I'm running is demo_pipeline.I'm using caiman_GUI in a linux environment to load mmap and hdf5 files so that no errors are reported, but I can't make changes to the roi. When I manipulate the same files in windows, caiman_GUI reports an error.
[cid:ed763c6f-9784-4efa-9557-e028703d9d5d]
________________________________
发件人: Pat Gunn ***@***.***>
发送时间: 2024年6月11日 3:37
收件人: flatironinstitute/CaImAn ***@***.***>
抄送: Shuqi Lu ***@***.***>; Author ***@***.***>
主题: Re: [flatironinstitute/CaImAn] linux run result file not readable in windows gui (Issue #1360)


Also, what are the filenames of the hdf5 and mmap files you're trying to load?

**Comment by pgunn** [comment]
Sorry for the delay in getting back to you; was out of the country for a scientific conference.

What are the filenames you were trying to load, and what versions of caiman are present on your linux side and the windows side?

**Comment by pgunn** [comment]
Closing due to inactivity
