### ISSUE TITLE
IndexError in update_temporal_components when running CNMF on images

### ISSUE THREAD

**Issue by DrDaheeJang** [flatironinstitute/CaImAn#1441]
Operating System (Linux, MacOS, Windows): Linux
Hardware type (x86, ARM..) and RAM: x86, 376 GB RAM
Python Version (e.g. 3.9): 3.10.15
Caiman version (e.g. 1.9.12): 1.11.3
How you installed Caiman (pure conda, conda + compile, colab, ..): conda

**Issue Description**
I encountered an IndexError while running the CNMF pipeline on imaging data with CaImAn v1.11.3. The error occurs during the update_temporal step inside the update_temporal_components function. This seems to happen when the code attempts to delete an invalid index from an array, causing the process to terminate unexpectedly.

The error is specifically triggered when using the parameters:

alpha_snmf=0.5
L1_ratio=0.1

These settings are important as they provide a clear representation of dendritic structures with minimal background noise. The same issue does not occur with other parameter values (e.g., alpha_snmf=100, L1_ratio=1.0), where the pipeline runs successfully.

**Error Log**
Traceback (most recent call last):
  File "RunCaimanDendritic.py", line 397, in <module>
    main()
  File "RunCaimanDendritic.py", line 379, in main
    cnm2, dims, param_string = run_cnmf(images, dims, dview, opts)
  File "RunCaimanDendritic.py", line 231, in run_cnmf
    cnm = cnm.fit(images)
  File "/usr/local/bin/anaconda3/envs/caiman-1-11-3/lib/python3.10/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 632, in fit
    self.update_temporal(Yr, use_init=False)
  File "/usr/local/bin/anaconda3/envs/caiman-1-11-3/lib/python3.10/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 882, in update_temporal
    self.estimates.g, self.estimates.YrA, self.estimates.lam = update_temporal_components(
  File "/usr/local/bin/anaconda3/envs/caiman-1-11-3/lib/python3.10/site-packages/caiman/source_extraction/cnmf/temporal.py", line 229, in update_temporal_components
    S = np.delete(S, list(ff), 0)
  File "/usr/local/bin/anaconda3/envs/caiman-1-11-3/lib/python3.10/site-packages/numpy/lib/function_base.py", line 5330, in delete
    raise IndexError(
IndexError: index 7 is out of bounds for axis 0 with size 5

Do you have any insights into what might be causing this issue? Is there a possible workaround or fix for this issue?

**Comment by pgunn** [comment]
What's the name of the CNMF Parameter you're using that you're calling L1_ratio here?

**Comment by DrDaheeJang** [comment]
@pgunn Thank you for your question!

The L1_ratio parameter in the code corresponds to the snmf_l1_ratio parameter within the CNMF options in CaImAn. It controls the regularization strength for the sparse NMF initialization, influencing the balance between L1 (sparsity) and L2 (smoothness) penalties.

In this script, I’ve set it to 0.1, which gives more weight to sparsity in the initialization process, as this can often work well for dendritic imaging data. If you’re working with a different data type or need a different trade-off, you might want to experiment with this parameter.

Let me know if you need further clarification!

**Comment by pgunn** [comment]
I'm not finding this within the current codebase or a sampling of older versions of the codebase.

Can you include a code snippet showing how you're setting this? It's possible that that parameter is not being consumed? If you'd like to just pastebin your RunCaimanDendridic that'd work.

**Comment by DrDaheeJang** [comment]
Our RunCaimanDendritic.py is just an adaptation of the demo. We modified params.py and initialization.py so we can just set l1_ratio like we do with alpha_snmf:
https://github.com/flatironinstitute/CaImAn/issues/1428#issuecomment-2511476289
 
We could upload the movie, the altered code, and the script somewhere if you'd like to try it.

**Comment by pgunn** [comment]
Oh! I had not realised you were the same person who had asked for the parameter to be threaded through to sklearn's NMF function (had actually forgotten about that request as well).

That changes things ; let me think about this further.

**Comment by pgunn** [comment]
Also, on that other request, we may eventually want to change a lot of how this works, but for now I think it probably makes sense to thread this parameter through and I'll look to do that soon.

**Comment by pgunn** [comment]
@DrDaheeJang I'm going to look at this in more detail now as we've added the l1_ratio configurability in the most recent release.

Is your data something you might reasonably be able to toss on Dropbox along with your modified notebook?

**Comment by DrDaheeJang** [comment]
Hi,
Thanks for your care on this matter.
I can share my data with you.
I'll get back to you soon!

Best,
D

**Comment by DrDaheeJang** [comment]
Hi,
Here is the data generating the error I reported.
https://www.dropbox.com/scl/fi/0vxt99jo0qjpisavufsy3/DJ032_20241111_00001.tif?rlkey=x3090fxsuzz2qb1zjfpqk4hhi&st=ehhrttt7&dl=0
Thank you for your help!

**Comment by pgunn** [comment]
@DrDaheeJang I'm grabbing it now; 32G is a bit big though; I'll test on this but it would've been fine to send a subset big enough to exhibit the issue without being this big.

Can you send me a link to the modified notebook too?

**Comment by DrDaheeJang** [comment]
Hi,

All my data files are the same size because I run the same task each time. I can’t trim them, as that would cause a loss of high-dimensional information, turning them into flat TIFF image sequences.

Also, each file has a different probability of encountering errors, and this particular file is the one that fails most frequently, so I’m sharing it with you.

Here’s the link with details on the code modifications and parameters we’re using:
https://github.com/flatironinstitute/CaImAn/issues/1428#issuecomment-2511476289

I’m curious to know if my file runs without errors on your setup.

Thanks!

**Comment by pgunn** [comment]
@DrDaheeJang I have the data ready to go, but the link you provided doesn't provide me enough information; what notebook were you running? Could you make your modified notebook available? Sorry for the fuss.

**Comment by DrDaheeJang** [comment]
@pgunn Hi, here is the python notebook https://www.dropbox.com/scl/fi/h5y84q8lkfh35msz7ap5y/RunCaimanDendritic.py?rlkey=43sqnd06kx6upsemyolc5fwe6&st=661a9eb9&dl=0
Thank you for your help!

**Comment by pgunn** [comment]
I started a run with your data after figuring out the right place to store the data for your script, and it ended up running for a long time, but it eventually ran out of RAM while doing setup_and_run_motion_correction() ; my workstation has a lot of RAM but apparently not enough.

I believe this happened after motion correction, while it was saving results, during the m_els.save(...) step.

Is this before or after you saw the index error?

**Comment by pgunn** [comment]
I'll find a system with more RAM to run it locally and get back to you.

**Comment by DrDaheeJang** [comment]
Thanks! Yes, I remember that motion-corrected mmap files were saved when I encountered the error, but no actual temporal or spatial components were saved as outputs.

**Comment by pgunn** [comment]
I reproduced the issue and am looking into it.

**Comment by DrDaheeJang** [comment]
Thanks for the updates!

**Comment by pgunn** [comment]
So I think what triggered the bug is that the (spatial, I think) background estimate has 3 components, and the third component is all zero. Two lines of inquiry:
A) Why did this happen, and
B) How can we better handle this?

I'm looking at that second part right now.

With the caveat that I don't know this part of the code well:
Right now these components are temporarily agglomerated into the mainline data for some calculations, and then we identify indices into the temporal components that reference zero values and which should be deleted. If some of those indices are part of the background, then parts of non-extended data structures get a deletion index past their size, causing the crash.

**Comment by pgunn** [comment]
@DrDaheeJang 
In your opts_dict, try setting nb to 2 rather than 3 and see if it makes a difference.

(even if this fixes it, it's still not great that the code crashes, but I'm curious if this will help)

**Comment by pgunn** [comment]
I spoke more with Kushal about this; having empty background components is something we should throw an exception over, telling people to reduce nb is the general right idea.

I'm going to add a check to the fit() method after it does run_CNMF_patches() to check for empty spatial and tell the user to adjust the parameters. We were looking into changing the filtering logic, but having empty background components could cause problems elsewhere in the code.

**Comment by DrDaheeJang** [comment]
I’m afraid the empty background issue is just with this specific data
because it has a poor signal-to-background noise ratio. Would you mind
doing a test run with another dataset of mine that has a good signal to see
whether it’s still an empty background issue?

**Comment by pgunn** [comment]
Sure. If you can send me another dataset as well as the script you're using with it (please send both - I really need the parameters), I can take a look.

(the issue you see with the other dataset is a similar looking error?)

**Comment by DrDaheeJang** [comment]
Here is new data with a good signal. You can test whether it has a zero
spatial index as well.

https://www.dropbox.com/scl/fi/n50hre8gf4vz0g70ido3w/DJ045_20250201_00003.tif?rlkey=9dk567xp63bk743tdp763sq3i&st=q6j5c2vi&dl=0

I’ve shared the Python code with you before, so I’m wondering which script
you’re asking for.
Also, my colleague tested the values 2, 3, and 4, but she said there was no
noticeable difference in the components and when it crashes, it doesn't
change anything..
I can try it myself and let you know how it works.

**Comment by DrDaheeJang** [comment]
I also tried the value 2 but encountered a new type of error—multiple 'RuntimeWarning' messages. It proceeded to the merging components step, then failed to generate mmap files, and ultimately resulted in a 'FileNotFoundError.' Do you have a chance to test my new dataset?

**Comment by pgunn** [comment]
Yes; I'm going to be experimenting with the new dataset today, and I'll also be looking at changing parameters for the earlier one.

**Comment by pgunn** [comment]
@DrDaheeJang I finished experimenting with the first dataset; with the current dev branch (which has a fix for a bug that perhaps you ran into relating to filenames) it does okay with nb=1 (I looked over the first dataset with @kushalkolar and he seems to agree that there's probably only one background component findable in that data); in a separate change that hasn't landed in dev yet, we'll throw an exception and catch this.

(it still bumps into a problem later in your script when you do an img.convert, but I'm not sure that's necessary)

I'll start experimenting with the second dataset today; it's taken me longer than ideal to do these experiments because doing a run takes awhile and it took some time to work through the relevant code. Hopefully this will take less time.

**Comment by pgunn** [comment]
@DrDaheeJang The code ran to completion with your second dataset and nb set to 1, at least with the code on my current working branch.

```
    67599193 [temporal.py:    update_iteration():381][37258] 114 out of total 116 temporal components updated
    67599241 [temporal.py:    update_iteration():381][37258] 115 out of total 116 temporal components updated
    67599289 [temporal.py:    update_iteration():381][37258] 116 out of total 116 temporal components updated
Detrending df/f
RGB components saved at: comp_root/DJ045/20250201/components_rf150MT95K50/RGB/component115.tiff
    67606650 [cluster.py:         stop_server():176][37258] stop_cluster(): done
Stacked image saved as multi-frame TIF at comp_root/DJ045/20250201/components_rf150MT95K50/8bitstack/pre_components_stack.tif
Completed in 18:46:10.635737
```
