### ISSUE TITLE
Numpy boolean subtract is deprecated

### ISSUE THREAD

**Issue by bringingheavendown** [flatironinstitute/CaImAn#145]
Trying to run demo_pipeline_cnmfE.py.  New install of Anaconda on Linux.   Python 3.6, Numpy 1.14.  Running in Spyder.  It runs for a while and then crashes.  

````
0 neurons have been initialized
In total,  7 neurons were initialized.
/home/honi/CaImAn/caiman/source_extraction/cnmf/deconvolution.py:1019: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  g = np.linalg.lstsq(A, xc[lags + 1:])[0]
Compute Background
0 neurons have been initialized
In total,  10 neurons were initialized.
Compute Background
In total,  9 neurons were initialized.
Compute Background
In total,  7 neurons were initialized.
Compute Background
Traceback (most recent call last):

  File "<ipython-input-1-5e95b0766364>", line 1, in <module>
    runfile('/home/honi/CaImAn/demos_detailed/demo_pipeline_cnmfE.py', wdir='/home/honi/CaImAn')

  File "/home/honi/anaconda3/envs/caiman/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "/home/honi/anaconda3/envs/caiman/lib/python3.6/site-packages/spyder/utils/site/sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/honi/CaImAn/demos_detailed/demo_pipeline_cnmfE.py", line 172, in <module>
    cnm.fit(Y)

  File "/home/honi/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 535, in fit
    del_duplicates=self.del_duplicates)

  File "/home/honi/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 256, in run_CNMF_patches
    file_res = dview.map_async(cnmf_patches, args_in).get(4294967)

  File "/home/honi/anaconda3/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value

TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
````

When running at the command line (`python demos_detailed/demo_pipeline_cnmfE.py`), extra debugging information is printed:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/honi/anaconda3/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/honi/anaconda3/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/honi/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 144, in cnmf_patches
    cnm = cnm.fit(images)
  File "/home/honi/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 432, in fit
    Y, sn=sn, options_total=options, **options['init_params'])
  File "/home/honi/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 344, in initialize_components
    center_psf=center_psf, options=options_total, sn=sn, nb=nb, ssub=ssub)
  File "/home/honi/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 996, in greedyROI_corr
    A, C, (d1, d2), int(np.round(ring_size_factor * gSiz)))
  File "/home/honi/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1578, in compute_W
    ring[1:-1, 1:-1] -= disk(radius, dtype=bool)
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "demos_detailed/demo_pipeline_cnmfE.py", line 172, in <module>
    cnm.fit(Y)
  File "/home/honi/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 535, in fit
    del_duplicates=self.del_duplicates)
  File "/home/honi/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 256, in run_CNMF_patches
    file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
  File "/home/honi/anaconda3/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
TypeError: numpy boolean subtract, the `-` operator, is deprecated, use the bitwise_xor, the `^` operator, or the logical_xor function instead.
```

**Comment by bringingheavendown** [comment]
Indeed replacing line 1578 in initialization.py with `ring[1:-1, 1:-1] = np.bitwise_xor(ring[1:-1, 1:-1], disk(radius, dtype=bool))` fixes the problem

**Comment by j-friedrich** [comment]
we can just use the default dtype (uint8) in `disk` instead of `bool`, which even shortens the code :)

**Comment by j-friedrich** [comment]
Closing. We actually fixed it already a while ago.
