### ISSUE TITLE
Memory Error when running local correlation pnr

### ISSUE THREAD

**Issue by Cumol** [flatironinstitute/CaImAn#283]
For better support, please use the template below to submit your issue.

- **Tell us about your operating system (Linux/macOS/Windows), Python version (2.7/3.x), and working environment (Spyder/Jupyter Notebook/other)**
Ubuntu 17.10, Python 3.6 using a Jupyter Notebook. 50Gb of RAM, 10Gb memmap

- **Describe the issue that you are experiencing**
Running the following code form the demo_pipeline_cnmfE.ipynb

```
# compute some summary images (correlation and peak to noise)
cn_filter, pnr = cm.summary_images.correlation_pnr(Y, gSig=gSig, swap_dim=False) # change swap dim if output looks weird, it is a problem with tiffile
# inspect the summary images and set the parameters
inspect_correlation_pnr(cn_filter,pnr)
```

Produces the following error:

```
---------------------------------------------------------------------------
MemoryError                               Traceback (most recent call last)
<ipython-input-8-4a96c503b882> in <module>()
      1 # compute some summary images (correlation and peak to noise)
----> 2 cn_filter, pnr = cm.summary_images.correlation_pnr(Y, gSig=gSig, swap_dim=False) # change swap dim if output looks weird, it is a problem with tiffile
      3 # inspect the summary images and set the parameters
      4 inspect_correlation_pnr(cn_filter,pnr)

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/summary_images.py in correlation_pnr(Y, gSig, center_psf, swap_dim, background_filter)
    331 
    332     # compute correlation image
--> 333     cn = local_correlations_fft(tmp_data, swap_dim=False)
    334 
    335     return cn, pnr

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/summary_images.py in local_correlations_fft(Y, eight_neighbours, swap_dim, opencv, rolling_window)
    121     if rolling_window is None:
    122         Y -= np.mean(Y, axis=0)
--> 123         Ystd = np.std(Y, axis=0)
    124         Ystd[Ystd == 0] = np.inf
    125         Y /= Ystd

~/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/fromnumeric.py in std(a, axis, dtype, out, ddof, keepdims)
   3005 
   3006     return _methods._std(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
-> 3007                          **kwargs)
   3008 
   3009 

~/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/_methods.py in _std(a, axis, dtype, out, ddof, keepdims)
    133 def _std(a, axis=None, dtype=None, out=None, ddof=0, keepdims=False):
    134     ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
--> 135                keepdims=keepdims)
    136 
    137     if isinstance(ret, mu.ndarray):

~/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/core/_methods.py in _var(a, axis, dtype, out, ddof, keepdims)
    110     # Note that x may not be inexact and that we need it to be an array,
    111     # not a scalar.
--> 112     x = asanyarray(arr - arrmean)
    113     if issubclass(arr.dtype.type, nt.complexfloating):
    114         x = um.multiply(x, um.conjugate(x), out=x).real

MemoryError: 


```

Checking the memory usage shows that all the memory of the system was used up. The error does not show up when using the endoscope demo file.

**Comment by agiovann** [comment]
@Cumol (@j-friedrich  can give you more tips) we are aware that CaImAn is currently not memory efficient for epifluorescence/1p data. Please consult the companion paper https://www.biorxiv.org/content/early/2018/06/05/339564, figure 8d. In your case, it is only a preprocessing step, so you might get away by checking the correlation image on a subset of the data to determine the values of min_corr and min_pnr. However, I forecast you will have problems if you do parallelize, I would suggest that with your file size and your memory you only use one process and not parallelize.

**Comment by epnev** [comment]
@agiovann @j-friedrich we could replace correlation image with [max correlation image](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/summary_images.py#L36) that is computed in chunks and less prone to memory issues. @j-friedrich do you want to do this?

**Comment by j-friedrich** [comment]
Can do, but the estimated threshold will then be biased to a larger value, as the CNMF-E algorithm uses and updates the filtered correlation image, not some max version. @Cumol, for now just follow Andrea's suggestion and determine the values of min_corr and min_pnr on a subset of the data.  Using patches but processing them sequentially by setting n_processes to 1 requires less RAM, but is slow -- or obviously just move to a machine with a large amount of RAM.

**Comment by Cumol** [comment]
@agiovann @j-friedrich I reduced the file size by going down to 5Hz instead of 10 and then ran the correlation image. This time it worked and I was able to adjust the values.

Running the CNMF however lead to following error:

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 154, in cnmf_patches
    cnm = cnm.fit(images)
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 453, in fit
    Y, sn=sn, options_total=options, **options['init_params'])
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/initialization.py", line 358, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/initialization.py", line 1112, in greedyROI_corr
    dview=None, **options['spatial_params'])
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/spatial.py", line 220, in update_spatial_components
    parallel_result = list(map(regression_ipyparallel, pixel_groups))
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/spatial.py", line 391, in regression_ipyparallel
    a_lrs = clf.fit(np.array(c.T), np.ravel(y))
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/linear_model/least_angle.py", line 699, in fit
    X, y = check_X_y(X, y, y_numeric=True, multi_output=True)
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/utils/validation.py", line 573, in check_X_y
    ensure_min_features, warn_on_dtype, estimator)
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/utils/validation.py", line 453, in check_array
    _assert_all_finite(array)
  File "/home/generalubuntu/anaconda3/envs/caiman/lib/python3.6/site-packages/sklearn/utils/validation.py", line 44, in _assert_all_finite
    " or a value too large for %r." % X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
"""

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
<ipython-input-10-6bfb3d3884cc> in <module>()
     27                 del_duplicates=True)                    # whether to remove duplicates from initialization
     28 
---> 29 cnm.fit(Y)

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images)
    562                                                                      gnb=self.gnb, border_pix=self.border_pix,
    563                                                                      low_rank_background=self.low_rank_background,
--> 564                                                                      del_duplicates=self.del_duplicates)
    565 
    566             # options = CNMFSetParms(Y, self.n_processes, p=self.p, gSig=self.gSig, K=A.shape[

~/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, options, rf, stride, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates)
    264     if dview is not None:
    265         if 'multiprocessing' in str(type(dview)):
--> 266             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    267         else:
    268             try:

~/anaconda3/envs/caiman/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

I then also set n_processes in CNMF to n_processes=1, but it still seemed to use all cores...

**Comment by epnev** [comment]
Try setting the `border_nan` variable during motion correction as described here:
https://github.com/flatironinstitute/CaImAn/issues/277
Also if you want to run with a single process you should set `dview=None` when running CNMF

**Comment by Cumol** [comment]
@epnev I did not do motion correction on this file because it did not need any. So the input was just a .tif file straight from ImageJ...

How do I deal with it if it is not motion corrected?

**Comment by agiovann** [comment]
@Cumol this is another issue. This issue should not be considered as a discussion thread. Open another issue if not solved. Do you happen to have NaNs in your original tif file?

**Comment by Cumol** [comment]
@agiovann not that I know of. Opening the .tif file in imageJ works fine. Any idea how I can check it?

**Comment by agiovann** [comment]
@Cumol np.sum(np.isnan(cm.load(tiffile_name))) should be 0 if there are no NaNs

**Comment by Cumol** [comment]
@agiovann running it with dview=None worked
