### ISSUE TITLE
Problem installing caimanmanager.py

### ISSUE THREAD

**Issue by agustinaf** [flatironinstitute/CaImAn#358]
Hello everyone, 

I'm new to python and CaImAn. I've encountered a problem while installing and need some help. 

I'm using Windows 10 (64x) and python 3.6. I installed the anaconda package and followed the instructions in the readme. 

When i get to this line of code: conda env create -f environment.yml -n caiman
The following message appears during "Executing transaction".

Executing transaction: \ DEBUG menuinst_win32:__init__(196): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'C:\Users\lab\Anaconda3\envs\caiman', env_name: 'caiman', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(320): Shortcut cmd is C:\Users\lab\Anaconda3\pythonw.exe, args are ['C:\\Users\\lab\\Anaconda3\\cwp.py', 'C:\\Users\\lab\\Anaconda3\\envs\\caiman', 'C:\\Users\\lab\\Anaconda3\\envs\\caiman\\pythonw.exe', 'C:\\Users\\lab\\Anaconda3\\envs\\caiman\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(320): Shortcut cmd is C:\Users\lab\Anaconda3\python.exe, args are ['C:\\Users\\lab\\Anaconda3\\cwp.py', 'C:\\Users\\lab\\Anaconda3\\envs\\caiman', 'C:\\Users\\lab\\Anaconda3\\envs\\caiman\\python.exe', 'C:\\Users\\lab\\Anaconda3\\envs\\caiman\\Scripts\\spyder-script.py', '--reset']
\ Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: ok

done
#
# To activate this environment, use
#
#     $ conda activate caiman
#
# To deactivate an active environment, use
#
#     $ conda deactivate

After this i'm able to activate caiman and finish the readme block. 

When i execute "caimanmanager.py install" I get the following error message:

(caiman) C:\Users\lab>caimanmanager.py install
Traceback (most recent call last):
  File "C:\Users\lab\caimanmanager.py", line 13, in <module>
    from caiman.paths import caiman_datadir
ModuleNotFoundError: No module named 'caiman.paths'

Also when i type in "dir". I don't see environment.yml in there. I tried this in two different computers and i get the same problem, so i'm sure i'm missing critical step. I just can't figure out what it is by myself. Any information will be very helpful to me. 

Thank You!!!

**Comment by agustinaf** [comment]
I didn't see any issues with that part or the rest of the block

**Comment by agustinaf** [comment]
This is what it says after pip install .
(caiman) C:\Users\lab\CaImAn>pip install .
Processing c:\users\lab\caiman
Building wheels for collected packages: caiman
  Running setup.py bdist_wheel for caiman ... done
  Stored in directory: C:\Users\lab\AppData\Local\Temp\pip-ephem-wheel-cache-r_rf1ipn\wheels\4d\c3\c4\e2370c2802314341939e7cb0bfea49f3fa43c75db0b4f740a8
Successfully built caiman
Installing collected packages: caiman
Successfully installed caiman-1.0

**Comment by pgunn** [comment]
Fascinating. So if you start a python interactive shell (type `python`) and from that type `import caiman`, what happens?

Is there any chance you closed the window you used to do the pip install and, in a second window (where you did not do a `conda activate caiman`) you tried to run caimanmanager? It's important with conda that any time you start a new shell and want to work with caiman, you activate the environment for that shell.

**Comment by agustinaf** [comment]
I think it imports it just fine:
(caiman) C:\Users\lab>python
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 11:48:23) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import caiman
>>>

Here is the whole thing done in the same anaconda prompt window:

(caiman) C:\Users\lab>git clone  https://github.com/flatironinstitute/CaImAn
fatal: destination path 'CaImAn' already exists and is not an empty directory.

(caiman) C:\Users\lab>cd CaImAn

(caiman) C:\Users\lab\CaImAn>conda env create -f environment.yml -n caiman

CondaValueError: prefix already exists: C:\Users\lab\Anaconda3\envs\caiman


(caiman) C:\Users\lab\CaImAn>activate caiman

C:\Users\lab\CaImAn>set KERAS_BACKEND=

C:\Users\lab\CaImAn>set "KERAS_BACKEND=theano"

(caiman) C:\Users\lab\CaImAn>pip install .
Processing c:\users\lab\caiman
Building wheels for collected packages: caiman
  Running setup.py bdist_wheel for caiman ... done
  Stored in directory: C:\Users\lab\AppData\Local\Temp\pip-ephem-wheel-cache-rz43tin_\wheels\4d\c3\c4\e2370c2802314341939e7cb0bfea49f3fa43c75db0b4f740a8
Successfully built caiman
Installing collected packages: caiman
  Found existing installation: caiman 1.0
    Uninstalling caiman-1.0:
      Successfully uninstalled caiman-1.0
Successfully installed caiman-1.0

(caiman) C:\Users\lab\CaImAn>copy caimanmanager.py ..
Overwrite ..\caimanmanager.py? (Yes/No/All): Yes
        1 file(s) copied.

(caiman) C:\Users\lab\CaImAn>conda install numba
Solving environment: done

# All requested packages already installed.


(caiman) C:\Users\lab\CaImAn>set KERAS_BACKEND=

(caiman) C:\Users\lab\CaImAn>set "KERAS_BACKEND=theano"

(caiman) C:\Users\lab\CaImAn>cd ..

(caiman) C:\Users\lab>caimanmanager.py install
Traceback (most recent call last):
  File "C:\Users\lab\caimanmanager.py", line 13, in <module>
    from caiman.paths import caiman_datadir
ModuleNotFoundError: No module named 'caiman'

(caiman) C:\Users\lab>

**Comment by pgunn** [comment]
Does `python caimanmanager.py install` yield the same result?

**Comment by agustinaf** [comment]
it gives a similar error:

(caiman) C:\Users\lab>python caimanmanager.py install --inplace
Traceback (most recent call last):
  File "caimanmanager.py", line 197, in <module>
    main()
  File "caimanmanager.py", line 165, in main
    do_install_to(cfg.userdir, cfg.inplace, cfg.force)
  File "caimanmanager.py", line 55, in do_install_to
    shutil.copytree(copydir, os.path.join(targdir, copydir))
  File "C:\Users\lab\Anaconda3\envs\caiman\lib\shutil.py", line 309, in copytree
    names = os.listdir(src)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'demos'

**Comment by pgunn** [comment]
That's actually a very different error.

The reason I asked you to do "python caimanmanager.py install" is that I believe you have in Windows' association editor an association of .py files with one of your existing python interpreter and so if you run a python program directly (by name), it's not finding the installed library, whereas if you say python from the commandline, you end up with Conda's python wrapper that runs things correctly.

So let's try that final command again, except without the `--inplace` flag, to see if that works better for you.

**Comment by agustinaf** [comment]
IT WORKED!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! wow thank you so much for your time and explanation! Now i can start exploring CaImAn, looking forward to this! :D

**Comment by pgunn** [comment]
One thing to look out for is that if you run the commandline demos (as opposed to the notebook ones), you'll always want to run them by explicitly saying "python demoname.py" rather than just "demoname.py"

Have fun!

**Comment by agustinaf** [comment]
Good to know, thank you!

**Comment by akim5651** [comment]
@pgunn 
Thank you for your help thus far - was able to activate the caiman env. I've been stuck with activating the caimanmanager.py file. With the caiman env activated, I have done the "pip install .", and am out of the caiman directory. As directed above, upon inputting 'python caimanmanger.py install', I've been getting:

(caiman) C:\Users\akimi>python caimanmanager.py install
Traceback (most recent call last):
  File "caimanmanager.py", line 12, in <module>
    from caiman.paths import caiman_datadir
  File "C:\Users\akimi\Anaconda3\envs\caiman\lib\site-packages\caiman\__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "C:\Users\akimi\Anaconda3\envs\caiman\lib\site-packages\caiman\base\movies.py", line 35, in <module>
    from skimage.transform import warp, AffineTransform
  File "C:\Users\akimi\Anaconda3\envs\caiman\lib\site-packages\skimage\__init__.py", line 177, in <module>
    from .data import data_dir
  File "C:\Users\akimi\Anaconda3\envs\caiman\lib\site-packages\skimage\data\__init__.py", line 15, in <module>
    from ..io import imread, use_plugin
  File "C:\Users\akimi\Anaconda3\envs\caiman\lib\site-packages\skimage\io\__init__.py", line 7, in <module>
    from .manage_plugins import *
  File "C:\Users\akimi\Anaconda3\envs\caiman\lib\site-packages\skimage\io\manage_plugins.py", line 28, in <module>
    from .collection import imread_collection_wrapper
  File "C:\Users\akimi\Anaconda3\envs\caiman\lib\site-packages\skimage\io\collection.py", line 14, in <module>
    from ..external.tifffile import TiffFile
  File "C:\Users\akimi\Anaconda3\envs\caiman\lib\site-packages\skimage\external\tifffile\__init__.py", line 1, in <module>
    from .tifffile import imsave, imread, imshow, TiffFile, TiffWriter, TiffSequence
  File "C:\Users\akimi\Anaconda3\envs\caiman\lib\site-packages\skimage\external\tifffile\tifffile.py", line 293, in <module>
    from . import _tifffile
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb

**Comment by pgunn** [comment]
@akim5651 
I believe this comes from having mixed conda-forge and default conda packages; we only recently realised that this is a very bad idea (after conversations with Conda developers).

If you do a `conda list` from inside your caiman environment, can you send me the full results? (Putting it on pastebin and sending the link is fine).

**Comment by akim5651** [comment]
I see. Sure thing:

`(caiman) C:\Users\akimi>cd caiman

(caiman) C:\Users\akimi\CaImAn>conda list
# packages in environment at C:\Users\akimi\Anaconda3\envs\caiman:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astroid                   2.1.0                 py36_1000    conda-forge
attrs                     18.2.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    1.5.0                    py36_0    conda-forge
bokeh                     1.0.2                 py36_1000    conda-forge
ca-certificates           2018.03.07                    0
caiman                    1.0                       <pip>
certifi                   2018.11.29               py36_0
cffi                      1.11.5          py36hfa6e2cd_1001    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
colorama                  0.4.1                      py_0    conda-forge
cryptography              2.3.1           py36h74b6da3_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.2          py36h6538335_1000    conda-forge
cytoolz                   0.9.0.1         py36hfa6e2cd_1001    conda-forge
dask-core                 1.0.0                      py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                 py36_1002    conda-forge
freetype                  2.7                      vc14_0    conda-forge
future                    0.17.0                py36_1000    conda-forge
h5py                      2.8.0           py36hf098a70_1005    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1003    conda-forge
html5lib                  0.9999999                py36_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                   py36_1000    conda-forge
imageio                   2.4.1                 py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
intel-openmp              2019.1                      144
ipykernel                 5.1.0           py36h39e3cac_1001    conda-forge
ipyparallel               6.2.3                 py36_1000    conda-forge
ipython                   7.2.0           py36h39e3cac_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                 py36_1000    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
keras                     2.1.5                    py36_0    conda-forge
keyring                   17.0.0                py36_1000    conda-forge
lazy-object-proxy         1.3.1           py36hfa6e2cd_1000    conda-forge
libgpuarray               0.7.6             hfa6e2cd_1003    conda-forge
libpng                    1.6.36            h7602738_1000    conda-forge
libprotobuf               3.6.1             h1a1b453_1000    conda-forge
libsodium                 1.0.16            h2fa13f4_1001    conda-forge
libtiff                   4.0.6                    vc14_6    conda-forge
libwebp                   0.5.2                         7    conda-forge
llvmlite                  0.26.0           py36ha925a31_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.0.7                      py_1    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.0           py36hfa6e2cd_1000    conda-forge
matplotlib                2.0.2                    py36_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
mkl                       2019.1                      144
msys2-conda-epoch         20160418                      1
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
networkx                  2.2                        py_1    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numba                     0.41.0           py36hf9181ef_0
numpy                     1.13.3           py36hb69e940_3
numpydoc                  0.8.0                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv                    3.2.0             np113py36_204    conda-forge
openssl                   1.0.2p               hfa6e2cd_0
packaging                 18.0                       py_0    conda-forge
pandoc                    2.5                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
peakutils                 1.3.0                      py_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    4.3.0                    py36_1    conda-forge
pims                      0.4.1                      py_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
protobuf                  3.6.1           py36he025d50_1001    conda-forge
psutil                    5.4.8           py36hfa6e2cd_1000    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pygpu                     0.7.6           py36h452e1ab_1000    conda-forge
pylint                    2.2.2                 py36_1000    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0           py36h764d66f_1007    conda-forge
pyreadline                2.1                   py36_1000    conda-forge
pyrsistent                0.14.7          py36hfa6e2cd_1000    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.6                he025d50_0    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
pywavelets                1.0.1           py36h452e1ab_1000    conda-forge
pywin32-ctypes            0.2.0                 py36_1000    conda-forge
pywinpty                  0.5.5                 py36_1000    conda-forge
pyyaml                    3.13            py36hfa6e2cd_1001    conda-forge
pyzmq                     17.1.2          py36hf576995_1001    conda-forge
qt                        5.6.2                h2639256_8    conda-forge
qtawesome                 0.5.3              pyh8a2030e_0    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
requests                  2.21.0                py36_1000    conda-forge
rope                      0.10.7                     py_1    conda-forge
scikit-image              0.14.1          py36h6538335_1001    conda-forge
scikit-learn              0.20.1           py36h343c172_0
scipy                     1.1.0            py36h29ff71c_2
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
sip                       4.18.1           py36h6538335_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
slicerator                0.9.8                      py_1    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    1.8.2                 py36_1000    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.2                 py36_1001    conda-forge
spyder-kernels            0.3.0                    py36_1    conda-forge
sqlite                    3.26.0            hfa6e2cd_1000    conda-forge
tensorboard               0.4.0rc3                 py36_2    conda-forge
tensorflow                1.4.0                    py36_0    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
theano                    1.0.3           py36h6538335_1001    conda-forge
tifffile                  0.15.1          py36h452e1ab_1001    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   4.5.3           py36hfa6e2cd_1001    conda-forge
tqdm                      4.28.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
typed-ast                 1.1.0           py36hfa6e2cd_1000    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
vs2015_win-64             14.0.25123           h17c34da_3    conda-forge
vs2017_win-64             19.15.26726          h3c6f0ee_0
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
win_inet_pton             1.0.1                 py36_1002    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.10.11         py36hfa6e2cd_1001    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zeromq                    4.2.5             he025d50_1006    conda-forge
zlib                      1.2.11            h2fa13f4_1003    conda-forge`

**Comment by akim5651** [comment]
I see. Sure thing:

```
(caiman) C:\Users\akimi>cd caiman

(caiman) C:\Users\akimi\CaImAn>conda list
# packages in environment at C:\Users\akimi\Anaconda3\envs\caiman:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astroid                   2.1.0                 py36_1000    conda-forge
attrs                     18.2.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.0                         mkl
bleach                    1.5.0                    py36_0    conda-forge
bokeh                     1.0.2                 py36_1000    conda-forge
ca-certificates           2018.03.07                    0
caiman                    1.0                       <pip>
certifi                   2018.11.29               py36_0
cffi                      1.11.5          py36hfa6e2cd_1001    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
colorama                  0.4.1                      py_0    conda-forge
cryptography              2.3.1           py36h74b6da3_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.2          py36h6538335_1000    conda-forge
cytoolz                   0.9.0.1         py36hfa6e2cd_1001    conda-forge
dask-core                 1.0.0                      py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                 py36_1002    conda-forge
freetype                  2.7                      vc14_0    conda-forge
future                    0.17.0                py36_1000    conda-forge
h5py                      2.8.0           py36hf098a70_1005    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1003    conda-forge
html5lib                  0.9999999                py36_0    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha66f8fd_1
idna                      2.8                   py36_1000    conda-forge
imageio                   2.4.1                 py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
intel-openmp              2019.1                      144
ipykernel                 5.1.0           py36h39e3cac_1001    conda-forge
ipyparallel               6.2.3                 py36_1000    conda-forge
ipython                   7.2.0           py36h39e3cac_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                 py36_1000    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
keras                     2.1.5                    py36_0    conda-forge
keyring                   17.0.0                py36_1000    conda-forge
lazy-object-proxy         1.3.1           py36hfa6e2cd_1000    conda-forge
libgpuarray               0.7.6             hfa6e2cd_1003    conda-forge
libpng                    1.6.36            h7602738_1000    conda-forge
libprotobuf               3.6.1             h1a1b453_1000    conda-forge
libsodium                 1.0.16            h2fa13f4_1001    conda-forge
libtiff                   4.0.6                    vc14_6    conda-forge
libwebp                   0.5.2                         7    conda-forge
llvmlite                  0.26.0           py36ha925a31_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
mako                      1.0.7                      py_1    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.0           py36hfa6e2cd_1000    conda-forge
matplotlib                2.0.2                    py36_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py36hfa6e2cd_1000    conda-forge
mkl                       2019.1                      144
msys2-conda-epoch         20160418                      1
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
networkx                  2.2                        py_1    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numba                     0.41.0           py36hf9181ef_0
numpy                     1.13.3           py36hb69e940_3
numpydoc                  0.8.0                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv                    3.2.0             np113py36_204    conda-forge
openssl                   1.0.2p               hfa6e2cd_0
packaging                 18.0                       py_0    conda-forge
pandoc                    2.5                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
peakutils                 1.3.0                      py_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    4.3.0                    py36_1    conda-forge
pims                      0.4.1                      py_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
protobuf                  3.6.1           py36he025d50_1001    conda-forge
psutil                    5.4.8           py36hfa6e2cd_1000    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pygpu                     0.7.6           py36h452e1ab_1000    conda-forge
pylint                    2.2.2                 py36_1000    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0           py36h764d66f_1007    conda-forge
pyreadline                2.1                   py36_1000    conda-forge
pyrsistent                0.14.7          py36hfa6e2cd_1000    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.6                he025d50_0    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.7                     py_0    conda-forge
pywavelets                1.0.1           py36h452e1ab_1000    conda-forge
pywin32-ctypes            0.2.0                 py36_1000    conda-forge
pywinpty                  0.5.5                 py36_1000    conda-forge
pyyaml                    3.13            py36hfa6e2cd_1001    conda-forge
pyzmq                     17.1.2          py36hf576995_1001    conda-forge
qt                        5.6.2                h2639256_8    conda-forge
qtawesome                 0.5.3              pyh8a2030e_0    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
requests                  2.21.0                py36_1000    conda-forge
rope                      0.10.7                     py_1    conda-forge
scikit-image              0.14.1          py36h6538335_1001    conda-forge
scikit-learn              0.20.1           py36h343c172_0
scipy                     1.1.0            py36h29ff71c_2
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
sip                       4.18.1           py36h6538335_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
slicerator                0.9.8                      py_1    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    1.8.2                 py36_1000    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.2                 py36_1001    conda-forge
spyder-kernels            0.3.0                    py36_1    conda-forge
sqlite                    3.26.0            hfa6e2cd_1000    conda-forge
tensorboard               0.4.0rc3                 py36_2    conda-forge
tensorflow                1.4.0                    py36_0    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
theano                    1.0.3           py36h6538335_1001    conda-forge
tifffile                  0.15.1          py36h452e1ab_1001    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   4.5.3           py36hfa6e2cd_1001    conda-forge
tqdm                      4.28.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
typed-ast                 1.1.0           py36hfa6e2cd_1000    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
vs2015_win-64             14.0.25123           h17c34da_3    conda-forge
vs2017_win-64             19.15.26726          h3c6f0ee_0
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
win_inet_pton             1.0.1                 py36_1002    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
winpty                    0.4.3                         4    conda-forge
wrapt                     1.10.11         py36hfa6e2cd_1001    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zeromq                    4.2.5             he025d50_1006    conda-forge
zlib                      1.2.11            h2fa13f4_1003    conda-forge
```

**Comment by pgunn** [comment]
@akim5651 

Yup, that's a mix of packages from conda-forge (the ones with that name on the right) and from defaults (without, excepting caiman itself).

You can either remove that environment, recreate it from yml, and any tweaks you need to redo can be done with `-c conda-forge --override-channels` or you can go through all the packages that are from defaults and replace them with conda-forge builds. (To fix the immediate problem, replacing numpy with a conda-forge version should do the trick but there may be further problems down the line you'll solve unless you do a complete clean)

**Comment by akim5651** [comment]
@pgunn 

Thanks for the explanation. I have tried to remove the environment, recreate it from the yml, getting the same error - is that what you meant by 'complete clean'? (Sorry, I am not well-versed in Python).

I then tried to install a conda-forge version of numpy:

```
(caiman) C:\Users\akimi>conda install -c conda-forge numpy
Solving environment: done

## Package Plan ##

  environment location: C:\Users\akimi\Anaconda3\envs\caiman

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    mkl_fft-1.0.10             |           py36_0         130 KB  conda-forge
    numpy-1.13.3               |   py36h5c71026_4         3.7 MB
    scikit-learn-0.20.1        |   py36hb854c30_0         5.2 MB
    scipy-1.1.0                |   py36hc28095f_0        13.5 MB
    mkl_random-1.0.2           |           py36_0         267 KB  conda-forge
    mkl-2018.0.3               |                1       178.1 MB
    ------------------------------------------------------------
                                           Total:       200.9 MB

The following NEW packages will be INSTALLED:

    mkl_fft:      1.0.10-py36_0         conda-forge
    mkl_random:   1.0.2-py36_0          conda-forge

The following packages will be UPDATED:

    numpy:        1.13.3-py36hb69e940_3             --> 1.13.3-py36h5c71026_4
    scikit-learn: 0.20.1-py36h343c172_0             --> 0.20.1-py36hb854c30_0

The following packages will be DOWNGRADED:

    mkl:          2019.1-144                        --> 2018.0.3-1
    scipy:        1.1.0-py36h29ff71c_2              --> 1.1.0-py36hc28095f_0

Proceed ([y]/n)? y
```
It looks like it keeps downloading the non conda-forge version.
Would it be possible to use CaImAn without the caimanmanager.py installation, or would you please be able to propose a more step-by-step approach to bypassing this? Would perhaps changing the yml file help?

**Comment by pgunn** [comment]
@akim5651 
Try this:

```conda install -c conda-forge --override-channels numpy```

**Comment by akim5651** [comment]
@pgunn 

```
(caiman) C:\Users\akimi>conda install -c conda-forge --override-channels numpy
Solving environment: done

# All requested packages already installed.
```

And from 'conda list' thereafter:

it shows: (snippet)
...
```
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numba                     0.41.0           py36hf9181ef_0
numpy                     1.13.3           py36h5c71026_4
numpydoc                  0.8.0                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
opencv                    3.2.0             np113py36_204    conda-forge
```
