### ISSUE TITLE
Unable to install caimanmanger on Fedora 28

### ISSUE THREAD

**Issue by galenlynch** [flatironinstitute/CaImAn#364]
As the title states, I am unable to install caimanager on fedora 28. I suspect it may have something to do with the fact that Fedora uses Wayland. Here is the error message that I receive:

```
(caiman) ~/D/C/CaImAn $ python caimanmanager.py install --inplace  
/home/glynch/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/font_manager.py:280: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  'Matplotlib is building the font cache using fc-list. '
Traceback (most recent call last):
  File "/home/glynch/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3.py", line 10, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "caimanmanager.py", line 13, in <module>
    from caiman.paths import caiman_datadir
  File "/home/glynch/Documents/Code/CaImAn/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "/home/glynch/Documents/Code/CaImAn/caiman/base/movies.py", line 44, in <module>
    import pylab as pl
  File "/home/glynch/anaconda3/envs/caiman/lib/python3.6/site-packages/pylab.py", line 1, in <module>
    from matplotlib.pylab import *
  File "/home/glynch/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/pylab.py", line 257, in <module>
    from matplotlib import cbook, mlab, pyplot as plt
  File "/home/glynch/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/home/glynch/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/home/glynch/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3cairo.py", line 6, in <module>
    from . import backend_gtk3
  File "/home/glynch/anaconda3/envs/caiman/lib/python3.6/site-packages/matplotlib/backends/backend_gtk3.py", line 12, in <module>
    raise ImportError("Gtk3 backend requires pygobject to be installed.")
ImportError: Gtk3 backend requires pygobject to be installed.
```
I tried linking my system gi package into the environment, but I got a symbol error, suggesting that the libraries are incompatible.

I am now trying to install pygobjects from the conda-forge channel, but in the process conda has decided to change a lot of other libraries, which makes me worried that I'll run into other cryptic bugs when using caiman. Here is the change set:

```
$ conda install -c conda-forge pygobject
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.10
  latest version: 4.5.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/glynch/anaconda3/envs/caiman

  added / updated specs: 
    - pygobject


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    hdf5-1.8.17                |               11         4.0 MB  conda-forge
    pycairo-1.13.3             |           py36_0         145 KB  conda-forge
    scikit-learn-0.19.1        |   py36hedc7406_0         5.2 MB
    opencv-3.2.0               |      np112py36_0        24.3 MB  conda-forge
    mkl-2018.0.3               |                1       198.7 MB
    numpy-1.12.1               |   py36he24570b_1         3.8 MB
    gobject-introspection-1.51.3|           py36_0         1.2 MB  conda-forge
    h5py-2.7.0                 |      np112py36_0         3.3 MB  conda-forge
    pygobject-3.25.1           |           py36_0         618 KB  conda-forge
    libgfortran-ng-7.2.0       |       hdf63c60_3         1.2 MB  conda-forge
    blas-1.0                   |              mkl           6 KB
    intel-openmp-2018.0.3      |                0         705 KB
    scipy-1.1.0                |   py36hc49cb51_0        18.1 MB
    ------------------------------------------------------------
                                           Total:       261.2 MB

The following NEW packages will be INSTALLED:

    gobject-introspection: 1.51.3-py36_0                     conda-forge
    intel-openmp:          2018.0.3-0                                   
    libgfortran-ng:        7.2.0-hdf63c60_3                  conda-forge
    mkl:                   2018.0.3-1                                   
    pycairo:               1.13.3-py36_0                     conda-forge
    pygobject:             3.25.1-py36_0                     conda-forge

The following packages will be UPDATED:

    scipy:                 0.19.1-py36_blas_openblas_202     conda-forge [blas_openblas] --> 1.1.0-py36hc49cb51_0             

The following packages will be DOWNGRADED:

    blas:                  1.1-openblas                      conda-forge --> 1.0-mkl                          
    h5py:                  2.7.1-py36_1                      conda-forge --> 2.7.0-np112py36_0     conda-forge
    hdf5:                  1.8.18-3                          conda-forge --> 1.8.17-11             conda-forge
    numpy:                 1.13.3-py36_blas_openblas_200     conda-forge [blas_openblas] --> 1.12.1-py36he24570b_1            
    opencv:                3.2.0-np113py36_blas_openblas_204 conda-forge [blas_openblas] --> 3.2.0-np112py36_0     conda-forge
    scikit-learn:          0.19.1-py36_blas_openblas_200     conda-forge [blas_openblas] --> 0.19.1-py36hedc7406_0   
```

**Comment by galenlynch** [comment]
I also needed to install gtk3 to get this to work:
```
conda install -c pkgw/label/superseded gtk3
```

**Comment by pgunn** [comment]
I am surprised that matplotlib requires gtk3 but doesn't have a dependency on it; that's probably a packaging bug. We'll need to poke the conda-forge devs about this. Thanks for letting us know.

You got it working?

**Comment by galenlynch** [comment]
To use opencv I had to do the following:
```bash
conda remove opencv
pip install opencv-python
```

Apparently the more recent versions of pip's opencv-python were built with support for video display on linux.

However, even though I don't get errors when I try to display the movie in the cnmf_e demo notebook, I just get a black screen that closes by itself after a minute or two.

**Comment by agiovann** [comment]
Just as a quick check. Could you tell me the output of

np.sum(np.isnan(your_movie))

?

**Comment by galenlynch** [comment]
I'm just trying to run the demo notebook for cnmf_e. Both the `Y` variable and the movie created from it seem to have no `nan`s. The rest of the pipeline works, the movie just doesn't display.

```python
np.sum(np.isnan(Y))
0
```

**Comment by galenlynch** [comment]
Just tried it on another ubuntu computer. Installation was painless, but the video was still black.

**Comment by epnev** [comment]
@galenlynch it might be your movie is too negative. Can you subtract its minimum value before trying to play it?

**Comment by galenlynch** [comment]
Sure, I'm just following the example notebook with the included example data. From what I can tell the notebook already subtracts the minimum from the first 100 frames. If I change it to subtract the minimum across the entire video, I still see a black video. 

For what it's worth I got it to show a video with my own data, so it might be some problem with the example?

**Comment by epnev** [comment]
Could be. Can you set `q_max=99` and `gain=1` and try again?

**Comment by agiovann** [comment]
@galenlynch if not solved yet, I wonder if this could be a jupyter related problem. Have you by any chance tried with ipython/spyder?

**Comment by pgunn** [comment]
@galenlynch Hi, what's the status of this issue? I'm hoping not to leave bugs open for too long without forward movement.

**Comment by galenlynch** [comment]
Sorry, I've been using the Matlab cnmfe package instead, and will close this issue until I can spend some time on reproducing it.
