### ISSUE TITLE
Kernel Error?

### ISSUE THREAD

**Issue by MarkCBenz** [flatironinstitute/CaImAn#388]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

Windows 10, Python 3.7, Jupyter Notebook

- **Describe the issue that you are experiencing**

Whenever I open the one of the .ipynb files housed in the \demos folder, I'm experiencing the "Kernel Error" copied below.

- **Copy error log below**
`Traceback (most recent call last):
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\web.py", line 1512, in _execute
    result = yield result
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\Users\mcbenz\Anaconda3\envs\caiman\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
`

I'm not quite sure what the issue is, since everything was working before.

**Comment by epnev** [comment]
@MarkCBenz closing due to inactivity. Feel free to reopen if your issue persists
