### ISSUE TITLE
The system cannot find the file specified

### ISSUE THREAD

**Issue by HunterTom94** [flatironinstitute/CaImAn#392]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message.
Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**

Hi, I am using Win10, python 3.6 in Jupyter Notebook.

- **Describe the issue that you are experiencing**

When I open Jupyter Notebook, in pipeline_demo.ipynb it says kernal error.

- **Copy error log below**

When I click the kernal error, error log is shown below.

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\web.py", line 1512, in _execute
    result = yield result
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\notebook\services\sessions\handlers.py", line 73, in post
    type=mtype))
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\tornado\gen.py", line 307, in wrapper
    yielded = next(result)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\jupyter_client\manager.py", line 259, in start_kernel
    **kw)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\jupyter_client\manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\site-packages\jupyter_client\launcher.py", line 128, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\envs\caiman\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

- **If you're not reporting an error, type your message below**

**Comment by agiovann** [comment]
@HunterTom94 As specified in the instruction, have you tried with dview=None?

**Comment by HunterTom94** [comment]
@agiovann I have not run the code yet, because when I open the .ipynb file, there is a kernal error. I am not able to run any code on JupyterNotebook.

**Comment by epnev** [comment]
Related to #388 
@pgunn could it be because we removed one of the .tif files recently? I wonder whether caimanmanager is looking for it.

**Comment by pgunn** [comment]
This is in the notebook; caimanmanager is a separate CLI util and doesn't really have moving parts when it's not being run. I patched caimanmanager sometime back.

**Comment by epnev** [comment]
@pgunn ok. Can you look into it?

**Comment by pgunn** [comment]
@HunterTom94 Does opening the other notebooks give you the same result? (it doesn't look like this is happening in any of our code)

**Comment by epnev** [comment]
@HunterTom94 Are you still facing this problem?

**Comment by HunterTom94** [comment]
@epnev I do not have other ipynb file to test with, but I worked around this by using running Jupyter on Ubuntu. I will not say problem is solved but I try not to deal with it at the moment. Sorry for the confusion.

**Comment by pgunn** [comment]
Hi,
For now we're closing this issue as it's not actively being debugged. If you'd like to work on it again, reopen or open a new issue.
