### ISSUE TITLE
pw_rigid fails in demo motion correction notebook

### ISSUE THREAD

**Issue by tbenst** [flatironinstitute/CaImAn#425]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), and working environment (Spyder/Jupyter Notebook/other)**
Jupyter notebook on Ubuntu 18.04

- **Describe the issue that you are experiencing**
When I run the demo_motion_correction notebook, rigid works but non-rigid fails with the following output:
```
       39102 [motion_correction.py:motion_correct_batch_pwrigid():2340] [32623] Adding to movie 296.0
       39103 [motion_correction.py:motion_correct_batch_pwrigid():2343] [32623] 0
       39104 [motion_correction.py:motion_correct_batch_pwrigid():2349] [32623] saving mmap of /home/tyler/caiman_data/example_movies/Sue_2x_3000_40_-46.tif
       39117 [motion_correction.py:motion_correction_piecewise():2544] [32623] **** MOVIE NOT SAVED BECAUSE num_splits is not None ****
       39118 [motion_correction.py:motion_correction_piecewise():2564] [32623] ** Starting parallel motion correction **
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/tyler/lib/anaconda3/envs/CaImAn/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/tyler/lib/anaconda3/envs/CaImAn/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/tyler/lib/anaconda3/envs/CaImAn/lib/python3.6/site-packages/caiman/motion_correction.py", line 2432, in tile_and_correct_wrapper
    use_cuda=use_cuda, border_nan=border_nan)
  File "/home/tyler/lib/anaconda3/envs/CaImAn/lib/python3.6/site-packages/caiman/motion_correction.py", line 1928, in tile_and_correct
    cv2.INTER_CUBIC, borderMode=cv2.BORDER_REPLICATE)
cv2.error: /feedstock_root/build_artefacts/opencv_1490907195496/work/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp:5043: error: (-215) ((map1.type() == CV_32FC2 || map1.type() == CV_16SC2) && map2.empty()) || (map1.type() == CV_32FC1 && map2.type() == CV_32FC1) in function remap

"""

The above exception was the direct cause of the following exception:

error                                     Traceback (most recent call last)
<ipython-input-11-2ad4fe85c9c5> in <module>
      3 mc.template = mc.mmap_file  # use the template obtained before to save in computation (optional)
      4 
----> 5 mc.motion_correct(save_movie=True, template=mc.total_template_rig)
      6 m_els = cm.load(mc.fname_tot_els)
      7 m_els.resize(1, 1, downsample_ratio).play(

~/lib/anaconda3/envs/CaImAn/lib/python3.6/site-packages/caiman/motion_correction.py in motion_correct(self, template, save_movie)
    223 
    224         if self.pw_rigid:
--> 225             self.motion_correct_pwrigid(template=template, save_movie=save_movie)
    226             b0 = np.ceil(np.maximum(np.max(np.abs(self.x_shifts_els)),
    227                                     np.max(np.abs(self.y_shifts_els))))

~/lib/anaconda3/envs/CaImAn/lib/python3.6/site-packages/caiman/motion_correction.py in motion_correct_pwrigid(self, save_movie, template, show_template)
    343                         num_splits_to_process=num_splits_to_process, num_iter=num_iter, template=self.total_template_els,
    344                         shifts_opencv=self.shifts_opencv, save_movie=save_movie, nonneg_movie=self.nonneg_movie, gSig_filt=self.gSig_filt,
--> 345                         use_cuda=self.use_cuda, border_nan=self.border_nan)
    346                 if show_template:
    347                     pl.imshow(new_template_els)

~/lib/anaconda3/envs/CaImAn/lib/python3.6/site-packages/caiman/motion_correction.py in motion_correct_batch_pwrigid(fname, max_shifts, strides, overlaps, add_to_movie, newoverlaps, newstrides, dview, upsample_factor_grid, max_deviation_rigid, splits, num_splits_to_process, num_iter, template, shifts_opencv, save_movie, nonneg_movie, gSig_filt, use_cuda, border_nan)
   2356                                                             base_name=os.path.split(fname)[-1][:-4] + '_els_', num_splits=num_splits_to_process,
   2357                                                             shifts_opencv=shifts_opencv, nonneg_movie=nonneg_movie, gSig_filt=gSig_filt,
-> 2358                                                             use_cuda=use_cuda, border_nan=border_nan)
   2359 
   2360         new_templ = np.nanmedian(np.dstack([r[-1] for r in res_el]), -1)

~/lib/anaconda3/envs/CaImAn/lib/python3.6/site-packages/caiman/motion_correction.py in motion_correction_piecewise(fname, splits, strides, overlaps, add_to_movie, template, max_shifts, max_deviation_rigid, newoverlaps, newstrides, upsample_factor_grid, order, dview, save_movie, base_name, subidx, num_splits, shifts_opencv, nonneg_movie, gSig_filt, use_cuda, border_nan)
   2567             dview.map(close_cuda_process, range(len(pars)))
   2568         elif 'multiprocessing' in str(type(dview)):
-> 2569             res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)
   2570         else:
   2571             res = dview.map_sync(tile_and_correct_wrapper, pars)

~/lib/anaconda3/envs/CaImAn/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

error: /feedstock_root/build_artefacts/opencv_1490907195496/work/opencv-3.2.0/modules/imgproc/src/imgwarp.cpp:5043: error: (-215) ((map1.type() == CV_32FC2 || map1.type() == CV_16SC2) && map2.empty()) || (map1.type() == CV_32FC1 && map2.type() == CV_32FC1) in function remap
```

I have installed caiman using the conda environment.yml file & installed caiman from github repo with pip. Let me know how I can help troubleshoot, thx!

**Comment by epnev** [comment]
@tbenst I wan't able to reproduce this error on a mac. From a quick google search the error looks like two variables are represented in different formats. If you run the demo_pipeline notebook, does the motion correction step go through or you get the same error?

@pgunn Does the demo_motion_correction notebook run without errors on linux?

**Comment by pgunn** [comment]
@epnev Yes, it runs fine on Linux. I removed and remade my env to test this.

**Comment by tbenst** [comment]
@epnev I can confirm that the same issue applies to demo_pipeline notebook. I have now tested on both Ubuntu and NixOS, and get the same errors on both.

**Comment by tbenst** [comment]
@pgunn, I presume you have opencv installed from conda via the environment.yml file? Here are my packages:

```
# packages in environment at /home/tyler/.conda/envs/caiman:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astroid                   2.1.0                 py36_1000    conda-forge
attrs                     18.2.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                    py36_0    conda-forge
bokeh                     1.0.3                 py36_1000    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
caiman                    1.0                       <pip>
cairo                     1.14.6                        4    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.2           py36hfc679d8_0    conda-forge
cytoolz                   0.9.0.1          py36h470a237_1    conda-forge
dask-core                 1.0.0                      py_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                 py36_1002    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
future                    0.17.1                py36_1000    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.51.4                        0    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         2    conda-forge
h5py                      2.7.0               np112py36_0    conda-forge
harfbuzz                  1.3.4                         2    conda-forge
hdf5                      1.8.17                       11    conda-forge
html5lib                  0.9999999                py36_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
imageio                   2.4.1                 py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipykernel                 5.1.0           py36h24bf2e0_1001    conda-forge
ipyparallel               6.2.3                 py36_1000    conda-forge
ipython                   7.2.0           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                 py36_1000    conda-forge
jasper                    1.900.1              hff1ad4c_5    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jeepney                   0.4                        py_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
keras                     2.1.5                    py36_0    conda-forge
keyring                   17.1.1                py36_1000    conda-forge
lazy-object-proxy         1.3.1            py36h470a237_0    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgpuarray               0.7.6                h470a237_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.36               ha92aebf_0    conda-forge
libprotobuf               3.6.1                hd28b015_0    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.7                         1    conda-forge
libwebp                   0.5.2                         7    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
mako                      1.0.7                      py_1    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.0            py36h470a237_0    conda-forge
matplotlib                2.0.2                    py36_2    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4            py36h470a237_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   5.9                          10    conda-forge
networkx                  2.2                        py_1    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numpy                     1.12.1          py36_blas_openblashb06ca3d_1  [blas_openblas]  conda-forge
numpydoc                  0.8.0                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3                ha44fe06_1    conda-forge
opencv                    3.2.0               np112py36_0    conda-forge
openssl                   1.0.2p               h470a237_2    conda-forge
packaging                 18.0                       py_0    conda-forge
pandoc                    2.5                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
peakutils                 1.3.0                      py_0    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    4.3.0                    py36_1    conda-forge
pims                      0.4.1                      py_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
protobuf                  3.6.1            py36hfc679d8_1    conda-forge
psutil                    5.4.8            py36h470a237_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pygpu                     0.7.6            py36h7eb728f_0    conda-forge
pylint                    2.2.2                 py36_1000    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0            py36h8210e8a_8    conda-forge
pyrsistent                0.14.9           py36h470a237_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.3                         1    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pywavelets                1.0.1            py36h7eb728f_0    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
pyzmq                     17.1.2           py36hae99301_1    conda-forge
qt                        5.6.2                         3    conda-forge
qtawesome                 0.5.5              pyh8a2030e_0    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.21.0                py36_1000    conda-forge
rope                      0.10.7                     py_1    conda-forge
scikit-image              0.14.1           py36hfc679d8_3    conda-forge
scikit-learn              0.20.2          py36_blas_openblash00c3548_400  [blas_openblas]  conda-forge
scipy                     1.2.0           py36_blas_openblashb06ca3d_200  [blas_openblas]  conda-forge
secretstorage             3.1.0                 py36_1001    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
slicerator                0.9.8                      py_1    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    1.8.3                 py36_1000    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.2                 py36_1001    conda-forge
spyder-kernels            0.3.0                 py36_1001    conda-forge
sqlite                    3.13.0                        1    conda-forge
tensorboard               0.4.0rc3                 py36_2    conda-forge
tensorflow                1.4.0                    py36_0    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
theano                    1.0.3            py36hfc679d8_1    conda-forge
tifffile                  0.15.1           py36h7eb728f_1    conda-forge
tk                        8.5.19                        2    conda-forge
toolchain                 2.4.0                         0    conda-forge
toolchain_c_linux-64      2.4.0                         0    conda-forge
toolchain_cxx_linux-64    2.4.0                         0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   4.5.3            py36h470a237_1    conda-forge
tqdm                      4.28.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
typed-ast                 1.1.1            py36h470a237_0    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.10.11          py36h470a237_1    conda-forge
wurlitzer                 1.0.2                 py36_1000    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by epnev** [comment]
@tbenst Thanks. We'll look into it.
@pgunn does anything look suspicious in this environment?

**Comment by pgunn** [comment]
@tbenst That's interesting. The environment I built ends up with a newer version of opencv. I'm puzzled why.

```
scclin009:~$ conda list
# packages in environment at /mnt/home/pgunn/miniconda3/envs/caiman:
#
# Name                    Version                   Build  Channel
absl-py                   0.6.1                 py36_1000    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astor                     0.7.1                      py_0    conda-forge
astroid                   2.1.0                 py36_1000    conda-forge
atk                       2.25.90              h05f3006_1    conda-forge
attrs                     18.2.0                     py_0    conda-forge
babel                     2.6.0                      py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    3.0.2                      py_1    conda-forge
bokeh                     1.0.3                 py36_1000    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
c-ares                    1.15.0               h470a237_1    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
caiman                    1.0                       <pip>
cairo                     1.14.12              h276e583_5    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.2           py36hfc679d8_0    conda-forge
cytoolz                   0.9.0.1          py36h470a237_1    conda-forge
dask-core                 1.0.0                      py_0    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                 py36_1002    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
ffmpeg                    4.1                  h9db10b5_0    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
future                    0.17.1                py36_1000    conda-forge
gast                      0.2.1                      py_0    conda-forge
gdk-pixbuf                2.36.12              h4ab6910_1    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.56.2               h464dc38_1    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gnutls                    3.6.5                ha0399c4_1    conda-forge
gobject-introspection     1.56.1           py36haaf12d0_1    conda-forge
graphite2                 1.3.13               hfc679d8_0    conda-forge
grpcio                    1.16.0           py36hd60e7a3_0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h5856ed1_0    conda-forge
gtk2                      2.24.31              hde048ef_0    conda-forge
h5py                      2.9.0            py36he5c79e1_0    conda-forge
harfbuzz                  1.9.0                h04dbb29_1    conda-forge
hdf5                      1.10.4          nompi_h5598ddc_1105    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
imageio                   2.4.1                 py36_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipykernel                 5.1.0           py36h24bf2e0_1001    conda-forge
ipyparallel               6.2.3                 py36_1000    conda-forge
ipython                   7.2.0           py36h24bf2e0_1000    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.4                 py36_1000    conda-forge
jasper                    1.900.1              hff1ad4c_5    conda-forge
jedi                      0.13.2                py36_1000    conda-forge
jeepney                   0.4                        py_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
jsonschema                3.0.0a3               py36_1000    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.4                      py_0    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
keras                     2.2.4                    py36_0    conda-forge
keras-applications        1.0.4                      py_1    conda-forge
keras-preprocessing       1.0.2                      py_1    conda-forge
keyring                   17.1.1                py36_1000    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
lazy-object-proxy         1.3.1            py36h470a237_0    conda-forge
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgpuarray               0.7.6                h470a237_3    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libpng                    1.6.36               ha92aebf_0    conda-forge
libprotobuf               3.6.1                hd28b015_0    conda-forge
libsodium                 1.0.16               h470a237_1    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.10               he6b73bb_1    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libwebp                   1.0.1                h08eee79_0    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
mako                      1.0.7                      py_1    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.1.0            py36h470a237_0    conda-forge
matplotlib                3.0.2            py36h8a2030e_1    conda-forge
matplotlib-base           3.0.2            py36h20b835b_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4            py36h470a237_0    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_2    conda-forge
nettle                    3.4.1                h470a237_2    conda-forge
networkx                  2.2                        py_1    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  5.7.4                 py36_1000    conda-forge
numpy                     1.15.4          py36_blas_openblashb06ca3d_0  [blas_openblas]  conda-forge
numpydoc                  0.8.0                      py_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openblas                  0.3.3                ha44fe06_1    conda-forge
opencv                    3.4.4           py36_blas_openblashae2c2e9_203  [blas_openblas]  conda-forge
openh264                  1.8.0                hd28b015_0    conda-forge
openssl                   1.0.2p               h470a237_2    conda-forge
packaging                 18.0                       py_0    conda-forge
pandoc                    2.5                           0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.40.14              he752989_2    conda-forge
parso                     0.3.1                      py_0    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
peakutils                 1.3.0                      py_0    conda-forge
pexpect                   4.6.0                 py36_1000    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pillow                    5.4.1            py36hc736899_0    conda-forge
pims                      0.4.1                      py_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
prometheus_client         0.5.0                      py_0    conda-forge
prompt_toolkit            2.0.7                      py_0    conda-forge
protobuf                  3.6.1            py36hfc679d8_1    conda-forge
psutil                    5.4.8            py36h470a237_0    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                 py36_1000    conda-forge
pycodestyle               2.4.0                      py_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyflakes                  2.0.0                      py_0    conda-forge
pygments                  2.3.1                      py_0    conda-forge
pygpu                     0.7.6            py36h7eb728f_0    conda-forge
pylint                    2.2.2                 py36_1000    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyqt                      5.6.0            py36h8210e8a_8    conda-forge
pyrsistent                0.14.9           py36h470a237_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.7                h5001a0f_1    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pywavelets                1.0.1            py36h7eb728f_0    conda-forge
pyyaml                    3.13             py36h470a237_1    conda-forge
pyzmq                     17.1.2           py36hae99301_1    conda-forge
qt                        5.6.2               h679f5bc_11    conda-forge
qtawesome                 0.5.5              pyh8a2030e_0    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
qtpy                      1.5.2              pyh8a2030e_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.21.0                py36_1000    conda-forge
rope                      0.10.7                     py_1    conda-forge
scikit-image              0.14.1           py36hfc679d8_3    conda-forge
scikit-learn              0.20.2          py36_blas_openblash00c3548_400  [blas_openblas]  conda-forge
scipy                     1.2.0           py36_blas_openblashb06ca3d_200  [blas_openblas]  conda-forge
secretstorage             3.1.0                 py36_1001    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.6.3                   py36_0    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.12.0                py36_1000    conda-forge
slicerator                0.9.8                      py_1    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    1.8.3                 py36_1000    conda-forge
sphinxcontrib-websupport  1.1.0                      py_1    conda-forge
spyder                    3.3.2                 py36_1001    conda-forge
spyder-kernels            0.3.0                 py36_1001    conda-forge
sqlite                    3.26.0               hb1c47c0_0    conda-forge
tensorboard               1.10.0                   py36_0    conda-forge
tensorflow                1.10.0                   py36_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.8.1                 py36_1001    conda-forge
testpath                  0.4.2                 py36_1000    conda-forge
theano                    1.0.3            py36hfc679d8_1    conda-forge
tifffile                  0.15.1           py36h7eb728f_1    conda-forge
tk                        8.6.9                ha92aebf_0    conda-forge
toolchain                 2.4.0                         0    conda-forge
toolchain_c_linux-64      2.4.0                         0    conda-forge
toolchain_cxx_linux-64    2.4.0                         0    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1            py36h470a237_0    conda-forge
tqdm                      4.28.1                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
typed-ast                 1.1.1            py36h470a237_0    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  0.14.1                     py_0    conda-forge
wheel                     0.32.3                   py36_0    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.10.11          py36h470a237_1    conda-forge
wurlitzer                 1.0.2                 py36_1000    conda-forge
x264                      1!152.20180717       h470a237_1    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-libxt                1.1.5                h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_6    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```

**Comment by pgunn** [comment]
@tbenst Sorry for asking this so late; what branch are you on? Apart from python, is anything pinned in your environment.yml?

**Comment by tbenst** [comment]
@pgunn I'm on master, where https://github.com/flatironinstitute/CaImAn/blob/master/environment.yml pins opencv=3.2. Will try 3.4, thanks!

**Comment by pgunn** [comment]
Ah, that's probably why. I'm on the dev branch. I've unpinned almost everything on that branch but we haven't merged that change back into master yet. Be very careful that if you install 3.4, you don't pull in packages from the default channel ; that's a swift (and sadly very easy) path to a lot of pain in conda.

**Comment by tbenst** [comment]
Happy to report that OpenCV 3.4 fixes the issue! Opened a pull request to update environment.yml.
