### ISSUE TITLE
Problems installing CaImAn with Pipenv

### ISSUE THREAD

**Issue by ChasNelson1990** [flatironinstitute/CaImAn#510]
So I'm trying to install CaImAn into my own project as a dependency.

My environments are set-up using pipfile. [Running Arch Linux 5.0.6 with Python 3.7.3 inside pipenv 2018.11.26]

I've tried a variety of approaches but can't get one to work.

N.B. it's entirely plausible this is a pipenv or even user-based problem but I thought I'd post it here in case anybody had an idea.

My pipfile:
```
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[dev-packages]
pytest = "*"
pylama = "*"
pep8 = "*"

[packages]
tensorflow = "*"
bokeh = "*"
cython = "*"
future = "*"
ipykernel = "~=4.10"
ipyparallel = "*"
jupyter = "*"
keras = "*"
matplotlib = "*"
mypy = "*"
nose = "*"
opencv-python = "*"
peakutils = "*"
pims = "*"
scikit-image = "*"
scikit-learn = "*"
spyder = "*"
tifffile = "*"
tqdm = "*"

[requires]
python_version = "3.7"
```

So, if I do the following it compiles fine (and unit tests run successfully).

```
git clone https://github.com/flatironinstitute/CaImAn.git
cd CaImAn
```
[add my Pipfile to the repo]

```
pipenv install --dev
pipenv install -e .
pipenv run python caimanmanager.py install --inplace
```
*But* if I do this inside my own project which has an existing Pipfile (no clashes as far I can see):

```
git clone https://github.com/flatironinstitute/CaImAn.git
```

[add above Pipfile to CaImAn subfolder]

```
pipenv install --dev
pipenv install -e ./CaImAn
```

I get the following exception (full traceback below):

>InstallationError: Command "python setup.py egg_info" failed with error code 1 in /home/chas/git/myrepo/CaImAn/

N.B. this doesn't work without the `-e` either because it doesn't seem to install dependencies from the subfolder Pipfile. I think this is expected pipenv behaviour.

*But*, this seems to be a pipenv-related issue (or my understanding of what's going on at least). Because if I do:

```
git clone https://github.com/flatironinstitute/CaImAn.git
```

[add above packages to main repo Pipfile]

```
pipenv install --dev
pipenv install ./CaImAn
pipenv run python caimanmanager.py install --inplace
```

Caiman appears to install properly but when discovering unit tests I get the following error:

> ImportError: cannot import name 'oasis' from 'caiman.source_extraction.cnmf' (/home/chas/git/myrepo/CaImAn/caiman/source_extraction/cnmf/__init__.py)

N.B. This doesn't work with the `-e` (same InstallationError as above).

I guess this means that the conda is doing something special that I'm not implementing here. Any suggestions would be welcome.

Full InstallationError traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 280, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 197, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 321, in prepare_editable_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /home/chas/git/myrepo/CaImAn/
File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 126, in <module>
    main()
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 119, in main
    parsed.requirements_dir, parsed.packages)
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 85, in _main
    requirements_dir=requirements_dir,
  File "/usr/lib/python3.7/site-packages/pipenv/resolver.py", line 69, in resolve
    req_dir=requirements_dir
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 726, in resolve_deps
    req_dir=req_dir,
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 480, in actually_resolve_deps
    resolved_tree = resolver.resolve()
  File "/usr/lib/python3.7/site-packages/pipenv/utils.py", line 385, in resolve
    results = self.resolver.resolve(max_rounds=environments.PIPENV_MAX_ROUNDS)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 206, in _resolve_one_round
    for dep in self._iter_dependencies(best_match):
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/resolver.py", line 280, in _iter_dependencies
    for dependency in self.repository.get_dependencies(ireq):
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 234, in get_dependencies
    legacy_results = self.get_legacy_dependencies(ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 426, in get_legacy_dependencies
    results, ireq = self.resolve_reqs(download_dir, ireq, wheel_cache)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 297, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 260, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/resolve.py", line 197, in _get_abstract_dist_for
    req, self.require_hashes, self.use_user_site, self.finder,
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 321, in prepare_editable_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/operations/prepare.py", line 127, in prep_for_dist
    self.req.run_egg_info()
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/req/req_install.py", line 474, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/usr/lib/python3.7/site-packages/pipenv/patched/notpip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pipenv.patched.notpip._internal.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /home/chas/git/myrepo/CaImAn/
```

**Comment by pgunn** [comment]
Hi,
My ability to support this is going to be limited - I have no experience with pipenv, and we already know Caiman is fairly sensitive to versions of some of the packages (currently only python 3.6 is supported). Still, it looks like pipenv has a `--verbose` flag as well as a `--support` flag that may provide more info as to what's going wrong. You also should probably specify `--python 3.6`.

As for not importing oasis, try removing the `--inplace` flag, and make sure you're not running caimanmanager from inside the source dir. There are some inflexibilities with the python search path that have complex interactions with the C++ components.

I'm still overseas and in a European time zone (will be getting back very late night on Wednesday), but if you want to hop on chat here there's a chance we can have a faster back-and-forth:
https://gitter.im/agiovann/Constrained_NMF
Note though that because this is going outside our supported install routes, I can't guarantee we'll be able to get you to a working setup. You've piqued my curiosity enough that I'd like to at least try some more on this.

**Comment by ChasNelson1990** [comment]
Thanks Pat, glad I've piqued your curiosity! This is a very long message but I think solves most things.

[And, I'm actually in the UK so you're perfectly in sync with me.]

Side note: I've found the following option for `pipenv install`: `--sequential`, which might be relevant re: your comment on tensorflow in `environment.yml`. It seems not to effect the problems we're talking about though so I'm not using it.

I've now set-up with python 3.6.8 (system the same otherwise) and done the following (the method that installed but didn't succeed with unit tests due to oasis):

```
git clone https://github.com/flatironinstitute/CaImAn.git
```

[add above packages to main repo Pipfile]

```
pipenv --support install --dev
pipenv --support install ./CaImAn
pipenv shell
python ./CaImAn/caimanmanager.py install
```

N.B. this means running caimanmanager.py is not run from any of the caiman repo folders.

And I get the oasis error:

> Traceback (most recent call last):
  File "./CaImAn/caimanmanager.py", line 14, in <module>
    from caiman.paths import caiman_datadir
  File "/home/chas/git/myRepo/CaImAn/caiman/__init__.py", line 3, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "/home/chas/git/myRepo/CaImAn/caiman/base/movies.py", line 68, in <module>
    from ..utils import visualization
  File "/home/chas/git/myRepo/CaImAn/caiman/utils/visualization.py", line 35, in <module>
    from ..summary_images import local_correlations
  File "/home/chas/git/myRepo/CaImAn/caiman/summary_images.py", line 31, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
  File "/home/chas/git/myRepo/CaImAn/caiman/source_extraction/cnmf/__init__.py", line 12, in <module>
    from . import oasis
ImportError: cannot import name 'oasis'

`--inplace` also gives the oasis error. Running the equivalent command from the CaImAn folder also gives the above error (with or without `--inplace`).

So, I retried with `--verbose` and it is *very verbose*, like longer than my shell caches. And it doesn't seem to pipe to a file with `2>&1`.

## Epiphany!

As writing this message I had a bit of an epiphany - this error should be:
>LocalUserError: problem exists between keyboard and chair!

The following is what I should have been doing:

```
git clone https://github.com/flatironinstitute/CaImAn.git
```

[add above packages to main repo Pipfile]

```
pipenv install --dev
pipenv install ./CaImAn
pipenv shell
caimanmanager.py install
```

By doing `python ./CaImAn/caimanmanager.py install` in the above versions, I was using the repo version of caimanmanager.py and not the installed version (as I had installed without `-e`). This seems to solve the oasis error.

To confirm everything was good, I ran

```
caimanmanager.py test
```

and got a load of FutureWarnings about non-tuple sequences for multidimensional indexing but ended with:

> Ran 9 tests in 103.301s
OK
Nosetests success!


## `-e`

This probably satisfies my needs for now but I also tried installing with  `-e`.

```
git clone https://github.com/flatironinstitute/CaImAn.git
```

[add above packages to main repo Pipfile]

```
pipenv install --dev
pipenv install -e ./CaImAn
```

Oddly I can't get any variant of `./CaImAn/caimanmanager.py install` (with or without `--inplace`) to work. Even after making sure `./CaIman/demos` is in the $PATH. I get the following error:

>Traceback (most recent call last):
  File "./CaImAn/caimanmanager.py", line 199, in <module>
    main()
  File "./CaImAn/caimanmanager.py", line 167, in main
    do_install_to(cfg.userdir, cfg.inplace, cfg.force)
  File "./CaImAn/caimanmanager.py", line 55, in do_install_to
    shutil.copytree(copydir, os.path.join(targdir, copydir))
  File "/home/chas/.local/share/virtualenvs/myRepo-FyH6KVfI/lib/python3.6/shutil.py", line 315, in copytree
    names = os.listdir(src)
FileNotFoundError: [Errno 2] No such file or directory: 'demos'

But if I run `caimanmanager.py install` for the non-`-e` virtual environment (created above) then `caimanmanager.py testl` runs with 9 successes!

**Comment by ChasNelson1990** [comment]
Additional:
I just reran the `pipenv install --dev` on a clean environment. The Pipfile now has an install line for caiman, either:

```
480c3f6 = {path = "./CaImAn"}
```

or (if installed with `-e`)

```
480c3f6 = {editable = true, path = "./CaImAn"}
```

I note that the first works. The second does not. Weird.
