### ISSUE TITLE
Tracking issue for Python 3.7 switchover

### ISSUE THREAD

**Issue by pgunn** [flatironinstitute/CaImAn#529]
This is a tracking issue for switching CaImAn over to building on Python 3.7. This will take part in two steps:
1) We change environment.yml (and any other needed files, including docs) so new environments start to be built this way, opening a period where we support both versions (existing users may upgrade caiman without rebuilding their environment)
2) We stop supporting Python 3.6 (and are comfortable using any features that require 3.7). This would take place at least a month or two after the first step, to give most of our userbase time to switch.

**Comment by pgunn** [comment]
Currently we're seeing issues with tensorflow packages in conda-forge built for 3.7 having a higher version glibc dependency than our local development environment (RHEL7, which has a fairly dated userland).

This is a known issue upstream and may be fixed there:
https://github.com/conda-forge/tensorflow-feedstock/issues/67

I have a workaround that involves switching to a tensorflow package from the defaults repo, and then forcing opencv to switch back to the conda-forge version, but this is annoyingly elaborate for our users and it may be better to wait until this is not necessary.

**Comment by epnev** [comment]
a tensorflow related error on my mac with 3.7:
```
Using TensorFlow backend.
/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.7
  return f(*args, **kwds)
       73826 [deprecation.py:            new_func():323][2956] From /Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
USING MODEL:/Users/epnevmatikakis/caiman_data/model/cnn_model.json
Traceback (most recent call last):

  File "<ipython-input-1-0b88d61731ab>", line 1, in <module>
    runfile('/Users/epnevmatikakis/Documents/Python/github/CaImAn/demos/general/demo_pipeline.py', wdir='/Users/epnevmatikakis/Documents/Python/github/CaImAn/demos/general')

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/Users/epnevmatikakis/Documents/Python/github/CaImAn/demos/general/demo_pipeline.py", line 263, in <module>
    main()

  File "/Users/epnevmatikakis/Documents/Python/github/CaImAn/demos/general/demo_pipeline.py", line 227, in main
    cnm2.estimates.evaluate_components(images, cnm2.params, dview=dview)

  File "/Users/epnevmatikakis/Documents/Python/github/CaImAn/caiman/source_extraction/cnmf/estimates.py", line 843, in evaluate_components
    min_SNR_reject=opts['SNR_lowest'])

  File "/Users/epnevmatikakis/Documents/Python/github/CaImAn/caiman/components_evaluation.py", line 479, in estimate_components_quality_auto
    thresh_cnn_min, thresh_cnn_lowest, use_cnn, gSig_range)

  File "/Users/epnevmatikakis/Documents/Python/github/CaImAn/caiman/components_evaluation.py", line 507, in select_components_from_metrics
    predictions, _ = evaluate_components_CNN(A, dims, gSig)

  File "/Users/epnevmatikakis/Documents/Python/github/CaImAn/caiman/components_evaluation.py", line 229, in evaluate_components_CNN
    loaded_model = model_from_json(loaded_model_json)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/keras/engine/saving.py", line 492, in model_from_json
    return deserialize(config, custom_objects=custom_objects)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/keras/engine/sequential.py", line 301, in from_config
    model.add(layer)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/keras/engine/sequential.py", line 181, in add
    output_tensor = layer(self.outputs[0])

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/keras/engine/base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/keras/layers/core.py", line 126, in call
    training=training)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 3105, in in_train_phase
    training = learning_phase()

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 135, in learning_phase
    name='keras_learning_phase')

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py", line 2093, in placeholder_with_default
    return gen_array_ops.placeholder_with_default(input, shape, name)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 5925, in placeholder_with_default
    "PlaceholderWithDefault", input=input, shape=shape, name=name)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 511, in _apply_op_helper
    preferred_dtype=default_dtype)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1175, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 304, in _constant_tensor_conversion_function
    return constant(v, dtype=dtype, name=name)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 245, in constant
    allow_broadcast=True)

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 283, in _constant_impl
    allow_broadcast=allow_broadcast))

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/tensorflow/python/framework/tensor_util.py", line 573, in make_tensor_proto
    append_fn(tensor_proto, proto_values)

  File "tensorflow/python/framework/fast_tensor_util.pyx", line 134, in tensorflow.python.framework.fast_tensor_util.AppendBoolArrayToTensorProto

  File "/Users/epnevmatikakis/anaconda3/envs/caiman37/lib/python3.7/site-packages/numpy/lib/type_check.py", line 547, in asscalar
    return a.item()

UnboundLocalError: local variable 'a' referenced before assignment
```

**Comment by tvajtay** [comment]
I'm having issues with oasis installing on Centos 7 on our cluster. Oasis doesn't show up on conda list after creating environment and created errors when trying to run `caimanmanager.py`

**Comment by pgunn** [comment]
@tvajtay Is this a 3.7 thing?

**Comment by tvajtay** [comment]
Nope, sorry, I'll open an issue.

**Comment by epnev** [comment]
@pgunn It appears that a new build of tensorflow is now available.
https://github.com/conda-forge/tensorflow-feedstock/pull/74

**Comment by pgunn** [comment]
Great. I'll test this.

One of the things we need to look into is whether https://github.com/conda-forge/caiman-feedstock/blob/master/recipe/meta.yaml will by default depend on conda-forge versions of packages or if things from defaults might get pulled in.

**Comment by epnev** [comment]
Working!
