### ISSUE TITLE
Merging components fails -- cnm.fit()

### ISSUE THREAD

**Issue by zoranne** [flatironinstitute/CaImAn#544]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

Linux/Python 3.6.8/Spyder/demo_pipeline_cnmfE.py

- **Describe the issue that you are experiencing**

cnm.fit(images) runs through until merging components, then returns an error. This seems to be a different issue to #255 since components were actually found (and the CaImAn version we're running is from 2019/05/02).

- **Copy error log below** With dview=dview

      135727 [merging.py:    merge_components():187][235219] Merging components [ 33  61  89 113 129 146 159]
      135754 [merging.py:    merge_components():187][235219] Merging components [ 95 132 133 148 149 185 190]
      135784 [merging.py:    merge_components():187][235219] Merging components [ 30  55  57  85 109 126]
Traceback (most recent call last):

  File "<ipython-input-9-22e6ef55c106>", line 2, in <module>
    cnm.fit(images)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 560, in fit
    indices=indices)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 245, in run_CNMF_patches
    file_res = dview.map_async(cnmf_patches, args_in).get(4294967)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value

ValueError: On entry to DLASCL parameter number 4 had an illegal value

- **Copy error log below** With dview=None

     1187016 [initialization.py:      greedyROI_corr():1000][157677] Merging components
     1187132 [merging.py:    merge_components():187][157677] Merging components [ 24  42  59  60  75  76  86  97 106 107 112 113 114 118 119 120]
     1187143 [merging.py:    merge_components():187][157677] Merging components [ 34  37  55  56  70  71  77  83  92  95  96 104 105 111]
Traceback (most recent call last):

  File "<ipython-input-10-8eddaaa4e2c4>", line 2, in <module>
    cnm.fit(images)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 560, in fit
    indices=indices)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 257, in run_CNMF_patches
    file_res = list(map(cnmf_patches, args_in))

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 135, in cnmf_patches
    cnm = cnm.fit(images)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 460, in fit
    self.initialize(Y)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 915, in initialize
    **self.params.get_group('init'))

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/initialization.py", line 316, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/initialization.py", line 1003, in greedyROI_corr
    dview=None, thr=options['merging']['merge_thr'], mx=np.Inf, fast_merge=True)[:2]

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/merging.py", line 209, in merge_components
    indx, temporal_params)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/merging.py", line 284, in merge_iteration
    np.array(computedC).squeeze(), g=None, **temporal_params)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/deconvolution.py", line 120, in constrained_foopsi
    method=noise_method, lags=lags, fudge_factor=fudge_factor)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/deconvolution.py", line 952, in estimate_parameters
    g = estimate_time_constant(fluor, p, sn, lags, fudge_factor)

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/caiman/source_extraction/cnmf/deconvolution.py", line 991, in estimate_time_constant
    g = np.linalg.lstsq(A, xc[lags + 1:], rcond=None)[0]

  File "/opt/anaconda/envs/apetzold/caiman-2019-05-02/lib/python3.6/site-packages/numpy/linalg/linalg.py", line 2236, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)

ValueError: On entry to DLASCL parameter number 4 had an illegal value

**Comment by epnev** [comment]
@zoranne I think this might be due to some NaN of Inf values that found their way into the calculations. See for example here https://github.com/statsmodels/statsmodels/issues/3596
How big is the dataset you're trying to analyze? If it's not too large it might be easier if I take a look directly at it to see where the error occurs.

**Comment by zoranne** [comment]
It's about 2 GB. I've uploaded it here: https://drive.google.com/open?id=12qViOBKkD-z56q3q04E7K4gNcGzSt1KO - does this work?

**Comment by epnev** [comment]
@zoranne That works yes. However I could not reproduce your error with the default parameters in the demo file. Can you also send the script that produces this error?

**Comment by zoranne** [comment]
Eventually, updating to the newest version solved the issue and now the issue does not reproduce.
