### ISSUE TITLE
Exception when running onACID demo

### ISSUE THREAD

**Issue by jordan-g** [flatironinstitute/CaImAn#560]
- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

MacOS 10.14
Python 3.7.3

- **Describe the issue that you are experiencing**

When running the included `demo_OnACID.py` (unmodified), I get an exception.

- **Copy error log below**

```
Expecting 500 components
[18, 100]
Traceback (most recent call last):
  File "onACID.py", line 107, in <module>
    main()
  File "onACID.py", line 85, in main
    cnm.fit_online()
  File "/usr/local/lib/python3.7/site-packages/caiman/source_extraction/cnmf/online_cnmf.py", line 710, in fit_online
    self.initialize_online()
  File "/usr/local/lib/python3.7/site-packages/caiman/source_extraction/cnmf/online_cnmf.py", line 657, in initialize_online
    self._prepare_object(Yr, T1)
  File "/usr/local/lib/python3.7/site-packages/caiman/source_extraction/cnmf/online_cnmf.py", line 188, in _prepare_object
    self.params.get('online', 'init_batch')].T.copy(), self.params.get('online', 'minibatch_shape'))
  File "/usr/local/lib/python3.7/site-packages/caiman/source_extraction/cnmf/online_cnmf.py", line 1345, in __new__
    raise Exception('The first dimension should equal num_els')
Exception: The first dimension should equal num_els
```

- **If you're not reporting an error, type your message below**

**Comment by jordan-g** [comment]
Nevermind, there was a small edit to the parameters that was causing this. Running the completely unmodified demo works fine.
