### ISSUE TITLE
Error on some datasets during extraction of DF/F values: 'cdf' referenced before assignment

### ISSUE THREAD

**Issue by SamBenezra** [flatironinstitute/CaImAn#613]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [wiki](https://github.com/flatironinstitute/CaImAn/wiki/Updating-CaImAn).

- **Tell us about your operating system (Linux/macOS/Windows), Python version (3.x), working environment (Spyder/Jupyter Notebook/other), and (if applicable) which of the demo scripts you're using for your analysis**

Linux/Python 3.6/Spyder

I attached the script I'm using. This is for dendritic imaging.

- **Describe the issue that you are experiencing**

While running some datasets, I get an error while extracting df/f traces.

- **Copy error log below**
WARNING:root:Percentile computation failed. Duplicating and trying again.
Oops!
Traceback (most recent call last):

  File "<ipython-input-1-ea8946dc8873>", line 1, in <module>
    runfile('/mnt/farscape/x1/sam/Python/demo_dendritic_sam.py', wdir='/mnt/farscape/x1/sam/Python')

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/mnt/farscape/x1/sam/Python/demo_dendritic_sam.py", line 232, in <module>
    main(merge_thr=0.95, rf = 150, K = 50, memap = True, date='07152019', animal = '6047-1')

  File "/mnt/farscape/x1/sam/Python/demo_dendritic_sam.py", line 188, in main
    cnm.estimates.detrend_df_f(quantileMin=8, frames_window=250)

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/estimates.py", line 659, in detrend_df_f
    detrend_only=detrend_only)

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py", line 372, in detrend_df_f
    data_prct, val = df_percentile(F[:, :frames_window], axis=1)

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/utils/stats.py", line 156, in df_percentile
    result = np.apply_along_axis(fnc, axis, inputData)

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/numpy/lib/shape_base.py", line 403, in apply_along_axis
    buff[ind] = asanyarray(func1d(inarr_view[ind], *args, **kwargs))

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/utils/stats.py", line 155, in fnc
    def fnc(x): return df_percentile(x)

  File "/home/sam/anaconda3/envs/caiman/lib/python3.6/site-packages/caiman/utils/stats.py", line 173, in df_percentile
    data_prct = cdf[np.argmax(density)]*100

UnboundLocalError: local variable 'cdf' referenced before assignment

- **If you're not reporting an error, type your message below**

[demo_dendritic_sam.txt](https://github.com/flatironinstitute/CaImAn/files/3469559/demo_dendritic_sam.txt)

**Comment by epnev** [comment]
@SamBenezra it should be fixed with https://github.com/flatironinstitute/CaImAn/commit/61e33dd710a49d0af249402256014727e6b37d79
