### ISSUE TITLE
OSError: Could not load meta information

### ISSUE THREAD

**Issue by SabriQ** [flatironinstitute/CaImAn#684]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
      linux(centos, 2TB RAM, so memory is definitely enough )
 2. Python version (3.x): 
     3.7.3
 3. Working environment (Python IDE/Jupyter Notebook/other):
    python script in anaconda
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
    caiman 1.0 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
   pip install .
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I have analysed video data of size less than ~20GB for many times, it worked very well.
and the error is the first time I analysed a data as large as 57GB with the same script and envs.
I have no idea about what's wrong.

- **Copy error log below**
Here is the log where the error begin. I guess it occur
    19028460 [motion_correction.py:tile_and_correct_wrapper():2922] [725001] 50
    19028732 [motion_correction.py:tile_and_correct_wrapper():2922] [725001] 60
    19028991 [motion_correction.py:tile_and_correct_wrapper():2922] [725001] 70
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 2916, in tile_and_correct_wrapper
    imgs = cm.load(img_name, subindices=idxs, var_name_hdf5=var_name_hdf5,is3D=is3D)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/base/movies.py", line 1421, in load
    pims_movie = pims.Video(file_name)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/pims/imageio_reader.py", line 34, in __init__
    self.reader = imageio.get_reader(filename, **kwargs)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/core/functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/core/format.py", line 164, in get_reader
    return self.Reader(self, request)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/core/format.py", line 214, in __init__
    self._open(**self.request.kwargs.copy())
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 322, in _open
    self._initialize()
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 465, in _initialize
    self._meta.update(self._read_gen.__next__())
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio_ffmpeg/_io.py", line 150, in read_frames
    raise IOError(fmt.format(err2))
OSError: Could not load meta information
=== stderr ===

ffmpeg version 4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdata/home/sqiu/script/pys/caiman_scripts/caiman_MotionCorrection_SourceExtraction.py", line 92, in <module>
    mc.motion_correct(save_movie=True)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 249, in motion_correct
    self.motion_correct_rigid(template=template, save_movie=save_movie)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 299, in motion_correct_rigid
    is3D=self.is3D)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 2724, in motion_correct_batch_rigid
    use_cuda=use_cuda, border_nan=border_nan, var_name_hdf5=var_name_hdf5, is3D=is3D)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 3026, in motion_correction_piecewise
    res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
OSError: Could not load meta information
=== stderr ===

ffmpeg version 4.1-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 6.3.0 (Debian 6.3.0-18+deb9u1) 20170516
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc-6 --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg
  libavutil      56. 22.100 / 56. 22.100
  libavcodec     58. 35.100 / 58. 35.100
  libavformat    58. 20.100 / 58. 20.100
  libavdevice    58.  5.100 / 58.  5.100
  libavfilter     7. 40.101 /  7. 40.101
  libswscale      5.  3.100 /  5.  3.100
  libswresample   3.  3.100 /  3.  3.100

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@SabriQ I think the problem here is that you're trying to analyze an .avi file that caiman cannot read neither with openCV nor with pims. 
- Can you try loading the first 100 frames using `cm.load(fname, subindices=slice(100))` where `fname` is the path to that file? It will probably fail.
- Besides size, is there anything different about this .avi file compared to other files you analyzed in the past?

**Comment by SabriQ** [comment]
- `cm.load(fname,` subindices=slice(100))'   it works, without any error.

- nothing besides size is different. all of them are .avi videos.

Questions:
  I run scripts in HPC which could have  many CPUs, twice for the same file with only different attributed CPUs. one was attributed with 60 CPUs and another has only 10. For Motion Correction part (break down at the end of Motion Correction), they have the same "Max Processes" , "Max Threads" and even nearly same CPU time. I am not sure about the multiprocess during Motion Correction. isn't  the more CPUs the faster?

**Comment by SabriQ** [comment]
there's one manipulation I forget to put. I tried twice with the same 57GB avi video data. The first time the error suggested me to "pip install imageio-ffmpeg" and I did it. Here is the error log of the first time,slightly different from the above.

    19595912 [motion_correction.py:tile_and_correct_wrapper():2922] [503103] 50
    19596166 [motion_correction.py:tile_and_correct_wrapper():2922] [503103] 60
    19596417 [motion_correction.py:tile_and_correct_wrapper():2922] [503103] 70
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 63, in _get_ffmpeg_api
    import imageio_ffmpeg
ModuleNotFoundError: No module named 'imageio_ffmpeg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 2916, in tile_and_correct_wrapper
    imgs = cm.load(img_name, subindices=idxs, var_name_hdf5=var_name_hdf5,is3D=is3D)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/base/movies.py", line 1421, in load
    pims_movie = pims.Video(file_name)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/pims/imageio_reader.py", line 34, in __init__
    self.reader = imageio.get_reader(filename, **kwargs)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/core/functions.py", line 143, in get_reader
    return format.get_reader(request)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/core/format.py", line 164, in get_reader
    return self.Reader(self, request)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/core/format.py", line 214, in __init__
    self._open(**self.request.kwargs.copy())
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 260, in _open
    self._ffmpeg_api = _get_ffmpeg_api()
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/imageio/plugins/ffmpeg.py", line 66, in _get_ffmpeg_api
    "To use the imageio ffmpeg plugin you need to "
ImportError: To use the imageio ffmpeg plugin you need to 'pip install imageio-ffmpeg'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfsdata/home/sqiu/script/pys/caiman_scripts/caiman_MotionCorrection_SourceExtraction.py", line 92, in <module>
    mc.motion_correct(save_movie=True)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 249, in motion_correct
    self.motion_correct_rigid(template=template, save_movie=save_movie)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 299, in motion_correct_rigid
    is3D=self.is3D)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 2724, in motion_correct_batch_rigid
    use_cuda=use_cuda, border_nan=border_nan, var_name_hdf5=var_name_hdf5, is3D=is3D)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/motion_correction.py", line 3026, in motion_correction_piecewise
    res = dview.map_async(tile_and_correct_wrapper, pars).get(4294967)
  File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ImportError: To use the imageio ffmpeg plugin you need to 'pip install imageio-ffmpeg'

I guess some thing is wrong with saving the motion-corrected videos. is it because its size?

**Comment by epnev** [comment]
@SabriQ 
It seems to me that your error occurs here:
```
File "/gpfsdata/home/sqiu/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/base/movies.py", line 1421, in load
pims_movie = pims.Video(file_name)
```

The fact that it goes there means that the code failed to load the file using openCV (which is the default choice). Then attempted to do it using pims which also failed. You can check the source code of [movies.py](https://github.com/flatironinstitute/CaImAn/blob/master/caiman/base/movies.py#L1592) to see that.

I'm not sure why this happening, typically openCV loads the file with no issues and the code doesn't need to call that line. I will search online to see if I can find an answer, but it seems very likely that it is a size related issue.

**Comment by epnev** [comment]
Two questions:
- What's your version of openCV (type in the terminal from your caiman environment `conda list opencv`
- Can you paste your motion correction parameters: `opts.motion`

**Comment by SabriQ** [comment]
' 
# dataset dependent parameters
fr = 30   
decay_time = 0.4                  
motion_correct = True           
# motion correction parameters
pw_rigid = False          
gSig_filt = (8,8)   
max_shifts = (25,25) 
strides = (96,96)  
overlaps = (32,32)  
max_deviation_rigid = 5 
border_nan = 'copy'
mc_dict = { 
    'fnames': fnames,
    'fr': fr, 
    'decay_time': decay_time,
    'pw_rigid': pw_rigid,
    'max_shifts': max_shifts,
    'gSig_filt': gSig_filt,
    'strides': strides,
    'overlaps': overlaps,
    'max_deviation_rigid': max_deviation_rigid,
    'border_nan': border_nan
}
opts = params.CNMFParams(params_dict=mc_dict)
'
yeah, I figure it out. it's the frame rate. I set wrong frame rate by accident. 
so it comes to the multiprocess. To accelerate the process of MotionCorrection or SourceExtraction, is it better to have as many CPUs as we can?

**Comment by epnev** [comment]
I'm glad it got resolved although I didn't understand what the problem was after all. In genera;, more CPUs will lead to faster processing. The only potential problem is that multiple CPUs will load chunks of the data in parallel, leading to higher memory requirements. All these can be regulated by relevant parameters, but in your case (with 2TB RAM) you probably won't encounter such issues.
