### ISSUE TITLE
Error in setting cnmf params

### ISSUE THREAD

**Issue by HoniSanders** [flatironinstitute/CaImAn#723]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows):  Linux cluster
 
 2. Python version (3.x): 3.6.7
 
 3. Working environment (Python IDE/Jupyter Notebook/other): python script
 
 4. Which of the demo scripts you're using for your analysis (if applicable): custom
 
 5. CaImAn version*: 1.8.1
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

```
Traceback (most recent call last):
  File "/home/honi/caiman-analysis//full_cnmfE.py", line 357, in <module>
    main()
  File "/home/honi/caiman-analysis//full_cnmfE.py", line 144, in main
    opts = params.CNMFParams(params_dict=mc_dict)
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/params.py", line 873, in __init__
    self.change_params(params_dict)
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/params.py", line 1044, in change_params
    self.check_consistency()
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/params.py", line 882, in check_consistency
    self.data['dims'] = get_file_size(self.data['fnames'], var_name_hdf5=self.data['var_name_hdf5'])[0]
  File "/home/honi/.conda/envs/caiman/lib/python3.6/site-packages/caiman/source_extraction/cnmf/utilities.py", line 1052, in get_file_size
    for fn in file_name])
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by pgunn** [comment]
Hello,
What led you to the above error?

**Comment by HoniSanders** [comment]
The problem was that the fnames entry in the params_dict was empty.
