### ISSUE TITLE
issue at cnm.fit(images)

### ISSUE THREAD

**Issue by SabriQ** [flatironinstitute/CaImAn#728]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 ubuntu16.04LTS
 2. Python version (3.x): 
 python 3.7.1
 3. Working environment (Python IDE/Jupyter Notebook/other):
 anaconda
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 caiman 1.0
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
`pip install -e .`
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

according to error log, it can not go through this code:
"cnm.fit(images)"
it might arise from the video. because the same script did work for some other videos.
if so, how can i detect which frame of the video is broken?

- **Copy error log below**
**
"""
Traceback (most recent call last):
  File "/home/qiushou/.conda/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/qiushou/.conda/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/qiushou/Documents/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 137, in cnmf_patches
    cnm = cnm.fit(images)
  File "/home/qiushou/Documents/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 505, in fit
    self.initialize(Y)
  File "/home/qiushou/Documents/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 964, in initialize
    **self.params.get_group('init'))
  File "/home/qiushou/Documents/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 331, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)
  File "/home/qiushou/Documents/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1055, in greedyROI_corr
    dview=None, dims=(d1, d2), **options['spatial_params'])
  File "/home/qiushou/Documents/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 240, in update_spatial_components
 65             M = -1
    parallel_result = list(map(regression_ipyparallel, pixel_groups))
  File "/home/qiushou/Documents/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 417, in regression_ipyparallel
    a_lrs = clf.fit(np.array(c.T), np.ravel(y))
  File "/home/qiushou/.conda/envs/caiman/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py", line 963, in fit
    X, y = check_X_y(X, y, y_numeric=True, multi_output=True)
  File "/home/qiushou/.conda/envs/caiman/lib/python3.7/site-packages/sklearn/utils/validation.py", line 722, in check_X_y
    dtype=None)
  File "/home/qiushou/.conda/envs/caiman/lib/python3.7/site-packages/sklearn/utils/validation.py", line 542, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/home/qiushou/.conda/envs/caiman/lib/python3.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "caiman_MotionCorrection_SourceExtraction.py", line 199, in <module>
    cnm.fit(images)
  File "/home/qiushou/Documents/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 605, in fit
    indices=indices)
  File "/home/qiushou/Documents/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 247, in run_CNMF_patches
    file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
  File "/home/qiushou/.conda/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 683, in get
    raise self._value
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
**

- **If you're not reporting an error, type your message below**

**Comment by epnev** [comment]
@SabriQ What is the value of `np.any(np.isnan(images))`?

**Comment by SabriQ** [comment]
> @SabriQ What is the value of np.any(np.isnan(images))?

False.
so it's not the video? 
in your opinion, what's the reason why it got a "ValueError"?

**Comment by epnev** [comment]
@SabriQ Since you're using a pip installer, I'm not sure how old your codebase. We've had some fixes for NaN values in the past that you might not have. Can you tell me what is the value of `opts.data['last_commit']`? This will show it.

You can also run the `fit` command with setting `dview=None` and copy the error log too see where the NaN value arises.

**Comment by SabriQ** [comment]
is the value of **opts.data['last_commit']** a string like “GITW-5a6717bc01cf4710a2a9fbf16346f75394d70325”. I export it from my script, and I have no idea about what it means.
I install caiman by Development mode Installation Process actually. 
**pip list | grep caiman** shows **caiman 1.0** 
and I also try install caiman by Package-based Process, **pip list | grep caiman** shows **caiman 1.8.3** in this situation.

**Comment by j-friedrich** [comment]
That's just an auto conversion warning and fine.


If you still get an error at line 417 in spatial.py (`a_lrs = clf.fit(np.array(c.T), np.ravel(y))`), you'd need to track down where the NaNs or infs arise. What are the passed values of c or y that triggers the Value Error?

(You can for example run in debug mode or  just wrap the line triggering the error in a try except clause and start the debugger to inspect the values
`try:`
 &ensp;&ensp;&ensp;&ensp;`a_lrs = clf.fit(np.array(c.T), np.ravel(y))`
`except:`
&ensp;&ensp;&ensp;&ensp;`import pdb; pdb.set_trace()`
)

**Comment by epnev** [comment]
@SabriQ You should put the full error log as what you posted does not contain an error message.

**Comment by akatav** [comment]
@is there a fix to this issue now ?

**Comment by epnev** [comment]
Closing due to inactivity (feel free to reopen if the issue persists)

**Comment by SabriQ** [comment]
sorry about months of inactivity. I have been stuck in home for months and have no access to the data because of the COVID-19. and I hope you are okay.
I read several other issues about NaNs, and `#513` ,`#517`,`#645`. there might be some candidate ways to solve my problems  even my error logs seems different from theirs.I will reply when I try them .
recently I compressed the data by ffmpeg, it made easier to cause the same problem. I hope this hint will hope you to optimize the method to solve this.I guess it might due to the blank patches where there are no components.

**Comment by SabriQ** [comment]
i found the same error log in issue `#323` but I just don't know how you figure it out

**Comment by SabriQ** [comment]
please reopen this issue if you see this reply. I think I will stick to this question these days.
thank you again .

**Comment by epnev** [comment]
@SabriQ You should open a new issue, describe the problem and post your error log. If you think it's related to past issue feel free to refer to them (without using the symbol `) so they become active links.
