### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by marcoistasy** [flatironinstitute/CaImAn#754]
1. Operating system (Linux/macOS/Windows): 
 MacOS

 2. Python version (3.x): 
 3.7.6

 3. Working environment (Python IDE/Jupyter Notebook/other):
Jupyter Notebook 

 4. Which of the demo scripts you're using for your analysis (if applicable):
 Modified version of `demo_pipeline_cnmfE`

 5. CaImAn version*: 
 Latest master branch.

 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
`pip install -e`

- **Describe the issue that you are experiencing**
I am running into an `index out of bounds` error when I am running the pipeline on a custom dataset. The issue exists whether `dview` is assigned or set to none.

- **Copy error log below**
```
IndexError                                Traceback (most recent call last)
<ipython-input-12-bc8d75c3649c> in <module>
      1 cnm = cnmf.CNMF(n_processes=n_processes, dview=None, Ain=Ain, params=opts)
----> 2 cnm.fit(images)

~/Documents/coding.nosync/CaImAn/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    604                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    605                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 606                     indices=indices)
    607 
    608             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~/Documents/coding.nosync/CaImAn/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    257 
    258     else:
--> 259         file_res = list(map(cnmf_patches, args_in))
    260 
    261     logging.info('Elapsed time for processing patches: \

~/Documents/coding.nosync/CaImAn/caiman/source_extraction/cnmf/map_reduce.py in cnmf_patches(args_in)
    135         cnm = cnmf.CNMF(n_processes=1, params=opts)
    136 
--> 137         cnm = cnm.fit(images)
    138         return [idx_, shapes, scipy.sparse.coo_matrix(cnm.estimates.A),
    139                 cnm.estimates.b, cnm.estimates.C, cnm.estimates.f,

~/Documents/coding.nosync/CaImAn/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    504             if self.estimates.A is None:
    505                 logging.info('initializing ...')
--> 506                 self.initialize(Y)
    507 
    508             if self.params.get('patch', 'only_init'):  # only return values after initialization

~/Documents/coding.nosync/CaImAn/caiman/source_extraction/cnmf/cnmf.py in initialize(self, Y, **kwargs)
    963                 extra_1p = initialize_components(
    964                     Y, sn=estim.sn, options_total=self.params.to_dict(),
--> 965                     **self.params.get_group('init'))
    966             try:
    967                 estim.S, estim.bl, estim.c1, estim.neurons_sn, \

~/Documents/coding.nosync/CaImAn/caiman/source_extraction/cnmf/initialization.py in initialize_components(Y, K, gSig, gSiz, ssub, tsub, nIter, maxIter, nb, kernel, use_hals, normalize_init, img, method_init, max_iter_snmf, alpha_snmf, sigma_smooth_snmf, perc_baseline_snmf, options_local_NMF, rolling_sum, rolling_length, sn, options_total, min_corr, min_pnr, ring_size_factor, center_psf, ssub_B, init_iter, remove_baseline, SC_kernel, SC_sigma, SC_thr, SC_normalize, SC_use_NN, SC_nnn, lambda_gnmf)
    345             Y, Y_ds, max_number=K, gSiz=gSiz[0], gSig=gSig[0], min_corr=min_corr, min_pnr=min_pnr,
    346             ring_size_factor=ring_size_factor, center_psf=center_psf, options=options_total,
--> 347             sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)
    348 
    349     elif method == 'sparse_nmf':

~/Documents/coding.nosync/CaImAn/caiman/source_extraction/cnmf/initialization.py in greedyROI_corr(Y, Y_ds, max_number, gSiz, gSig, center_psf, min_corr, min_pnr, seed_method, min_pixel, bd, thresh_init, ring_size_factor, nb, options, sn, save_video, video_name, ssub, ssub_B, init_iter)
   1182                                  tuple([ssub] * len(dims))).ravel() / tsub) / ssub,
   1183             b_in=np.zeros((d1 * d2, 0), np.float32),
-> 1184             dview=None, dims=(d1, d2), **options['spatial_params'])
   1185         A = A.astype(np.float32)
   1186         logging.info('Updating temporal components')

~/Documents/coding.nosync/CaImAn/caiman/source_extraction/cnmf/spatial.py in update_spatial_components(Y, C, f, A_in, sn, dims, min_size, max_size, dist, normalize_yyt_one, method_exp, expandCore, dview, n_pixels_per_process, medw, thr_method, maxthr, nrgthr, extract_cc, b_in, se, ss, nb, method_ls, update_background_components, low_rank_background, block_size_spat, num_blocks_per_run_spat)
    238             dview.results.clear()
    239     else:
--> 240         parallel_result = list(map(regression_ipyparallel, pixel_groups))
    241     data:List = []
    242     rows:List = []

~/Documents/coding.nosync/CaImAn/caiman/source_extraction/cnmf/spatial.py in regression_ipyparallel(pars)
    391     As = []
    392     for y, px, idx_px_from_0 in zip(Y, idxs_Y, range(len(idxs_C))):
--> 393         c = C[idxs_C[idx_px_from_0], :]
    394         idx_only_neurons = idxs_C[idx_px_from_0]
    395         if len(idx_only_neurons) > 0:

IndexError: index 53 is out of bounds for axis 0 with size 53
```

**Comment by pgunn** [comment]
Hi,
what can you tell us about that custom dataset? Is it something you can share with us? If not we'll at least want to know its characteristics.

**Comment by marcoistasy** [comment]
@pgunn Which features of the dataset would be important? The file size is ~500MB (.tif). Changing up the parameters a bit, I was able to fix the `IndexError` but ran into another one `TypeError: 'numpy.float64' object cannot be interpreted as an integer`/

**Comment by pgunn** [comment]
can you give me the line number of that typeerror?
We'd want to know the parameters you used, as well as the dimensions of the image and number of frames.

**Comment by marcoistasy** [comment]
Below is the full traceback:

```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/istasym/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/istasym/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/istasym/Documents/coding.nosync/external/CaImAn/caiman/source_extraction/cnmf/map_reduce.py", line 137, in cnmf_patches
    cnm = cnm.fit(images)
  File "/Users/istasym/Documents/coding.nosync/external/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 506, in fit
    self.initialize(Y)
  File "/Users/istasym/Documents/coding.nosync/external/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 965, in initialize
    **self.params.get_group('init'))
  File "/Users/istasym/Documents/coding.nosync/external/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 347, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter)
  File "/Users/istasym/Documents/coding.nosync/external/CaImAn/caiman/source_extraction/cnmf/initialization.py", line 1146, in greedyROI_corr
    dview=None, dims=(d1, d2), **options['spatial_params'])
  File "/Users/istasym/Documents/coding.nosync/external/CaImAn/caiman/source_extraction/cnmf/spatial.py", line 224, in update_spatial_components
    for i in range(0, np.prod(dims) - n_pixels_per_process + 1, n_pixels_per_process):
TypeError: 'numpy.float64' object cannot be interpreted as an integer
"""

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
<ipython-input-28-3a9d1245878c> in <module>
      1 # Perform CNMF
      2 cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, Ain=Ain, params=opts)
----> 3 cnm.fit(images)

~/Documents/coding.nosync/external/CaImAn/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    604                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    605                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 606                     indices=indices)
    607 
    608             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~/Documents/coding.nosync/external/CaImAn/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    245     if dview is not None:
    246         if 'multiprocessing' in str(type(dview)):
--> 247             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    248         else:
    249             try:

~/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    681             return self._value
    682         else:
--> 683             raise self._value
    684 
    685     def _set(self, i, obj):

TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

The image has 3133 frames (396x396).

When I run this script (https://github.com/etterguillaume/PIMPN) the processing succeeds; however, I am unable to save the output HDF5. Any idea where the issue might be?

**Comment by pgunn** [comment]
Do you mind making a small edit here?

/Users/istasym/Documents/coding.nosync/external/CaImAn/caiman/source_extraction/cnmf/spatial.py

Go to line 224, and right after this:

```
    logging.info('Updating Spatial Components using lasso lars')
    cct = np.diag(C.dot(C.T))
    pixel_groups = []
```

Please add:
```
print(f"DIMENSIONS:{dims}")
```

And then go look for that in the output. I'd like to verify that the dimensions are somehow getting a non-integer value; if they are I'll dig back through the code to see why they're not integer and find a way to force them to be.

**Comment by epnev** [comment]
@marcoistasy If you post your movie somewhere we might be able to figure out what's going wrong.

**Comment by epnev** [comment]
@marcoistasy Closing due to inactivity. If you're still facing this error re-open and provide a link to a file so we can reproduce.

**Comment by shuocao818** [comment]
Hi, I think I am experiencing a very similar problem at the refitting step (see below). I was applying the demo_pipline notebook on my dataset without changing any of the parameters. I can send my data file. Thanks a lot!

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-24-5b55c37df751> in <module>
      1 #%% RE-RUN seeded CNMF on accepted patches to refine and perform deconvolution
----> 2 cnm2 = cnm.refit(images, dview=dview)

/opt/miniconda3/envs/cnmf/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py in refit(self, images, dview)
    415         cnm.estimates = estimates
    416         cnm.mmap_file = self.mmap_file
--> 417         return cnm.fit(images)


    418 
    419     def fit(self, images, indices=(slice(None), slice(None))):

/opt/miniconda3/envs/cnmf/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    541 
    542             logging.info('update spatial ...')
--> 543             self.update_spatial(Yr, use_init=True)
    544 
    545             logging.info('update temporal ...')

/opt/miniconda3/envs/cnmf/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py in update_spatial(self, Y, use_init, **kwargs)
    933             update_spatial_components(Y, C=self.estimates.C, f=self.estimates.f, A_in=self.estimates.A,
    934                                       b_in=self.estimates.b, dview=self.dview,
--> 935                                       sn=self.estimates.sn, dims=self.dims, **self.params.get_group('spatial'))
    936 
    937         return self

/opt/miniconda3/envs/cnmf/lib/python3.7/site-packages/caiman/source_extraction/cnmf/spatial.py in update_spatial_components(Y, C, f, A_in, sn, dims, min_size, max_size, dist, normalize_yyt_one, method_exp, expandCore, dview, n_pixels_per_process, medw, thr_method, maxthr, nrgthr, extract_cc, b_in, se, ss, nb, method_ls, update_background_components, low_rank_background, block_size_spat, num_blocks_per_run_spat)
    267             if low_rank_background:
    268                 background_ff = list(filter(lambda i: i >= nb, ff - nr))
--> 269                 f = np.delete(f, background_ff, 0)
    270             else:
    271                 background_ff = list(filter(lambda i: i >= 0, ff - nr))

<__array_function__ internals> in delete(*args, **kwargs)

/opt/miniconda3/envs/cnmf/lib/python3.7/site-packages/numpy/lib/function_base.py in delete(arr, obj, axis)
   4404         else:
   4405             keep = ones(N, dtype=bool)
-> 4406             keep[obj,] = False
   4407 
   4408         slobj[axis] = keep

IndexError: index 3 is out of bounds for axis 0 with size 2

**Comment by owenrandlett** [comment]
Hi - I am getting a very similar error. I am also trying to run the notebook "demo_pipeline" on my own dataset, which is 512x512, 6087 frames, uint16, cytoplasmic GCaMP6s in a zebrafish brain. 

when I run :: 

#%%capture
#%% RE-RUN seeded CNMF on accepted patches to refine and perform deconvolution 
cnm2 = cnm.refit(images, dview=dview)

I get :: 


IndexError                                Traceback (most recent call last)
<ipython-input-17-20160aadac01> in <module>
      1 #%%capture
      2 #%% RE-RUN seeded CNMF on accepted patches to refine and perform deconvolution
----> 3 cnm2 = cnm.refit(images, dview=dview)

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in refit(self, images, dview)
    415         cnm.estimates = estimates
    416         cnm.mmap_file = self.mmap_file
--> 417         return cnm.fit(images)
    418 
    419     def fit(self, images, indices=(slice(None), slice(None))):

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in fit(self, images, indices)
    541 
    542             logging.info('update spatial ...')
--> 543             self.update_spatial(Yr, use_init=True)
    544 
    545             logging.info('update temporal ...')

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\cnmf.py in update_spatial(self, Y, use_init, **kwargs)
    934             update_spatial_components(Y, C=self.estimates.C, f=self.estimates.f, A_in=self.estimates.A,
    935                                       b_in=self.estimates.b, dview=self.dview,
--> 936                                       sn=self.estimates.sn, dims=self.dims, **self.params.get_group('spatial'))
    937 
    938         return self

~\Anaconda3\envs\caiman\lib\site-packages\caiman\source_extraction\cnmf\spatial.py in update_spatial_components(Y, C, f, A_in, sn, dims, min_size, max_size, dist, normalize_yyt_one, method_exp, expandCore, dview, n_pixels_per_process, medw, thr_method, maxthr, nrgthr, extract_cc, b_in, se, ss, nb, method_ls, update_background_components, low_rank_background, block_size_spat, num_blocks_per_run_spat)
    267             if low_rank_background:
    268                 background_ff = list(filter(lambda i: i >= nb, ff - nr))
--> 269                 f = np.delete(f, background_ff, 0)
    270             else:
    271                 background_ff = list(filter(lambda i: i >= 0, ff - nr))

<__array_function__ internals> in delete(*args, **kwargs)

~\Anaconda3\envs\caiman\lib\site-packages\numpy\lib\function_base.py in delete(arr, obj, axis)
   4404         else:
   4405             keep = ones(N, dtype=bool)
-> 4406             keep[obj,] = False
   4407 
   4408         slobj[axis] = keep

IndexError: index 2 is out of bounds for axis 0 with size 2
