### ISSUE TITLE
Issues when downloading caimanmanager.py

### ISSUE THREAD

**Issue by Hanbing1999** [flatironinstitute/CaImAn#773]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 windows
 2. Python version (3.x): 
 Python 3.7.6
 3. Working environment (Python IDE/Jupyter Notebook/other):
 cmd, anaconda prompt
 4. Which of the demo scripts you're using for your analysis (if applicable):
not known
 5. CaImAn version*: 
 Sorry, I don't know the meaning of creating a 'params' object. Does that mean I should creat a py file or just run it in cmd?
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
pip install -e 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

I first downloaded caimanmanager.py by using `conda install caimanmanager.py` in my home directory as shown here. `(caiman1) where caimanmanager.py
C:\Users\Hanbing\caimanmanager.py` * my caiman environment is named as caiman1. 
Then, in the environment of caiman1, I used `python caimanmanager.py install --inplace` to add this package to caiman1. But it reported an error [FileNotFoundError: [WinError 3]]. 
Then, I also ran `caimanmanager.py check`, but I don't know what the meaning is, since I am totally new to python. 
Thanks for your help! 

- **Copy error log below**

Install error 
`(caiman1) python caimanmanager.py install --inplace
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
Traceback (most recent call last):
  File "caimanmanager.py", line 272, in <module>
    main()
  File "caimanmanager.py", line 230, in main
    do_install_to(cfg.userdir, cfg.inplace, cfg.force)
  File "caimanmanager.py", line 66, in do_install_to
    shutil.copytree(copydir, os.path.join(targdir, copydir))
  File "D:\Python_install\envs\caiman1\lib\shutil.py", line 318, in copytree
    names = os.listdir(src)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'demos'`

(caiman1) caimanmanager.py check
`(caiman1) caimanmanager.py check
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\python\framework\dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
OK`

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Continued from #418 , just try that install again - it shouldn't fail the same way again.

**Comment by Hanbing1999** [comment]
> Continued from #418 , just try that install again - it shouldn't fail the same way again.

Ok, thanks! Now I can download this, but it reports another error. Does that matter? 
`Downloading and Extracting Packages
caiman-1.8.3         | 116.1 MB  | #######################################7 |  99% WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename D:\Python_install\pkgs\caiman-1.8.3-py37h3bbf574_0\share\caiman\docs\img\benchmarking.png.  Please remove this file manually (you may need to reboot to free file handles)
WARNING conda.gateways.disk.delete:unlink_or_rename_to_trash(140): Could not remove or rename D:\Python_install\pkgs\caiman-1.8.3-py37h3bbf574_0\share\caiman\docs\img\benchmarking.png.  Please remove this file manually (you may need to reboot to free file handles)
caiman-1.8.3         | 116.1 MB  | ######################################## | 100%
qtconsole-4.7.5      | 88 KB     | ######################################## | 100%

InvalidArchiveError('Error with archive D:\\Python_install\\pkgs\\caiman-1.8.3-py37h3bbf574_0.tar.bz2.  You probably need to delete and re-download or re-create this file.  Message from libarchive was:\n\nCould not unlink')`

**Comment by pgunn** [comment]
By any chance are you almost out of free disk space?

**Comment by Hanbing1999** [comment]
> By any chance are you almost out of free disk space?

It could be possible. It shows I only have 55.0GB in C: available. I will try it again. Now I activate caiman1 again, but how can I verify I indeed download caiman-1.8.3 properly?

**Comment by pgunn** [comment]
Remove the environment, do a `conda clean --all`, and then remake the environment using the command I gave you above. If you make it through without error, that's a good sign.

**Comment by Hanbing1999** [comment]
> Remove the environment, do a conda clean --all, and then remake the environment using the command I gave you above. If you make it through without error, that's a good sign.

I wonder if `conda clean --all` could affect other environments? For example, I also downloaded another env, Suite2p in my laptop.

**Comment by pgunn** [comment]
There are few ironclad guarantees in computing, but it should not; that's supposed to clear out data not currently used by any environment.

**Comment by Hanbing1999** [comment]
> There are few ironclad guarantees in computing, but it should not; that's supposed to clear out data not currently used by any environment.

Ok, I have tried it. But it still has some errors. It seems that I should not run it in cmd. Does that matters? Thanks for your time! 
`- DEBUG menuinst_win32:__init__(199): Menu: name: 'Anaconda${PY_VER} ${PLATFORM}', prefix: 'D:\Python_install\envs\caiman1', env_name: 'caiman1', mode: 'user', used_mode: 'user'
DEBUG menuinst_win32:create(323): Shortcut cmd is D:\Python_install\pythonw.exe, args are ['D:\\Python_install\\cwp.py', 'D:\\Python_install\\envs\\caiman1', 'D:\\Python_install\\envs\\caiman1\\pythonw.exe', 'D:\\Python_install\\envs\\caiman1\\Scripts\\spyder-script.py']
DEBUG menuinst_win32:create(323): Shortcut cmd is D:\Python_install\python.exe, args are ['D:\\Python_install\\cwp.py', 'D:\\Python_install\\envs\\caiman1', 'D:\\Python_install\\envs\\caiman1\\python.exe', 'D:\\Python_install\\envs\\caiman1\\Scripts\\spyder-script.py', '--reset']
done`

**Comment by pgunn** [comment]
If it didn't give you any real errors (what you pasted above was more debug messages), you probably have a working environment and can now try `caimanmanager.py install` to get you a working data directory.

**Comment by Hanbing1999** [comment]
> If it didn't give you any real errors (what you pasted above was more debug messages), you probably have a working environment and can now try caimanmanager.py install to get you a working data directory.

Thanks. It seems that works. Then I run `caimanmanager.py check` to check. 
`Traceback (most recent call last):
  File "C:\Users\Hanbing\caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
  File "D:\Python_install\envs\caiman1\lib\site-packages\caiman\__init__.py", line 4, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "D:\Python_install\envs\caiman1\lib\site-packages\caiman\base\movies.py", line 62, in <module>
    from ..utils import visualization
  File "D:\Python_install\envs\caiman1\lib\site-packages\caiman\utils\visualization.py", line 37, in <module>
    from ..summary_images import local_correlations
  File "D:\Python_install\envs\caiman1\lib\site-packages\caiman\summary_images.py", line 23, in <module>
    from caiman.source_extraction.cnmf.pre_processing import get_noise_fft
  File "D:\Python_install\envs\caiman1\lib\site-packages\caiman\source_extraction\cnmf\__init__.py", line 3, in <module>
    from . import utilities
  File "D:\Python_install\envs\caiman1\lib\site-packages\caiman\source_extraction\cnmf\utilities.py", line 39, in <module>
    from .initialization import greedyROI
  File "D:\Python_install\envs\caiman1\lib\site-packages\caiman\source_extraction\cnmf\initialization.py", line 42, in <module>
    from ...utils.utils import parmap
  File "D:\Python_install\envs\caiman1\lib\site-packages\caiman\utils\utils.py", line 34, in <module>
    import tensorflow as tf
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_core\__init__.py", line 46, in <module>
    from . _api.v2 import compat
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_core\_api\v2\compat\__init__.py", line 39, in <module>
    from . import v1
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_core\_api\v2\compat\v1\__init__.py", line 32, in <module>
    from . import compat
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\__init__.py", line 39, in <module>
    from . import v1
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\v1\__init__.py", line 29, in <module>
    from tensorflow._api.v2.compat.v1 import app
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_core\_api\v2\compat\__init__.py", line 39, in <module>
    from . import v1
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_core\_api\v2\compat\v1\__init__.py", line 32, in <module>
    from . import compat
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\__init__.py", line 39, in <module>
    from . import v1
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_core\_api\v2\compat\v1\compat\v1\__init__.py", line 667, in <module>
    from tensorflow_estimator.python.estimator.api._v1 import estimator
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1 import estimator
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py", line 10, in <module>
    from tensorflow_estimator._api.v1.estimator import experimental
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_estimator\_api\v1\estimator\experimental\__init__.py", line 10, in <module>
    from tensorflow_estimator.python.estimator.canned.dnn import dnn_logit_fn_builder
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_estimator\python\estimator\canned\dnn.py", line 33, in <module>
    from tensorflow_estimator.python.estimator import estimator
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_estimator\python\estimator\estimator.py", line 53, in <module>
    from tensorflow_estimator.python.estimator import util as estimator_util
  File "D:\Python_install\envs\caiman1\lib\site-packages\tensorflow_estimator\python\estimator\util.py", line 75, in <module>
    class _DatasetInitializerHook(tf.compat.v1.train.SessionRunHook):
AttributeError: module 'tensorflow' has no attribute 'compat'`

**Comment by epnev** [comment]
@Hanbing1999 Any updates on this? Where you able to install caimanmanager properly?

**Comment by epnev** [comment]
closing due to inactivity.
