### ISSUE TITLE
Still getting indexing issue

### ISSUE THREAD

**Issue by smbaca** [flatironinstitute/CaImAn#846]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows):  OS X Big Sur
 
 2. Python version (3.x): 3.7.9 by conda-forge
 
 3. Working environment (Python IDE/Jupyter Notebook/other): Jupyter Notebook
 
 4. Which of the demo scripts you're using for your analysis (if applicable): adaptation of cnmfe_pipeline_demo
 
 5. CaImAn version*: 1.8.5
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda):  conda install through anaconda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**
I can run the modified script with some custom datsets and not with others. When I used the demo .tif it also works. It appears that when I put the .tifs into ImageJ or open with graphic converter the tiff files appear to differ but I can't convert to get my multi-page tiffs to work. I am fine to send the actual tiff file as well as screenshots of what Graphic Converter sees as different between the demo tiff that works and my file that does not.

- **Copy error log below**
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/smbaca/opt/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/Users/smbaca/opt/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/Users/smbaca/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py", line 137, in cnmf_patches
    cnm = cnm.fit(images)
  File "/Users/smbaca/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 506, in fit
    self.initialize(Y)
  File "/Users/smbaca/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py", line 966, in initialize
    **self.params.get_group('init'))
  File "/Users/smbaca/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/initialization.py", line 354, in initialize_components
    sn=sn, nb=nb, ssub=ssub, ssub_B=ssub_B, init_iter=init_iter, seed_method=seed_method)
  File "/Users/smbaca/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/initialization.py", line 1264, in greedyROI_corr
    dview=None, dims=(d1, d2), **options['spatial_params'])
  File "/Users/smbaca/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/spatial.py", line 269, in update_spatial_components
    f = np.delete(f, background_ff, 0)
  File "<__array_function__ internals>", line 6, in delete
  File "/Users/smbaca/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/numpy/lib/function_base.py", line 4406, in delete
    keep[obj,] = False
IndexError: index 5 is out of bounds for axis 0 with size 0
"""

The above exception was the direct cause of the following exception:

IndexError                                Traceback (most recent call last)
<timed eval> in <module>

~/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/cnmf.py in fit(self, images, indices)
    604                     low_rank_background=self.params.get('patch', 'low_rank_background'),
    605                     del_duplicates=self.params.get('patch', 'del_duplicates'),
--> 606                     indices=indices)
    607 
    608             self.estimates.bl, self.estimates.c1, self.estimates.g, self.estimates.neurons_sn = None, None, None, None

~/opt/anaconda3/envs/caiman/lib/python3.7/site-packages/caiman/source_extraction/cnmf/map_reduce.py in run_CNMF_patches(file_name, shape, params, gnb, dview, memory_fact, border_pix, low_rank_background, del_duplicates, indices)
    245     if dview is not None:
    246         if 'multiprocessing' in str(type(dview)):
--> 247             file_res = dview.map_async(cnmf_patches, args_in).get(4294967)
    248         else:
    249             try:

~/opt/anaconda3/envs/caiman/lib/python3.7/multiprocessing/pool.py in get(self, timeout)
    655             return self._value
    656         else:
--> 657             raise self._value
    658 
    659     def _set(self, i, obj):

IndexError: index 5 is out of bounds for axis 0 with size 0

- **If you're not reporting an error, type your message below**

**Comment by agiovann** [comment]
Not sure if this helps, but you can load in ImageJ and save the image as a new tif file. In general this is well interpreted by CaImAn.
