### ISSUE TITLE
Installation error - installing CaImAnmanager.py

### ISSUE THREAD

**Issue by Teabelly** [flatironinstitute/CaImAn#872]
- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Windows

Does it have to be 32-bit ?

 2. Python version (3.x): 
 3.8 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
Conda

- **Describe the issue that you are experiencing**

When trying to install caimanmanager I get an error -  I have tried: 

updating python with: conda update python

Installing numpy with: conda install -c conda-forge numpy

- **Copy error log below**

(caiman) PS C:\Users\Callu> python C:\Users\Callu\anaconda3\envs\caiman\bin\caimanmanager.py install
Traceback (most recent call last):
  File "C:\Users\Callu\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 138, in <module>
    from . import _distributor_init
  File "C:\Users\Callu\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\Callu\anaconda3\envs\caiman\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "C:\Users\Callu\anaconda3\envs\caiman\bin\caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
  File "C:\Users\Callu\anaconda3\envs\caiman\lib\site-packages\caiman\__init__.py", line 4, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "C:\Users\Callu\anaconda3\envs\caiman\lib\site-packages\caiman\base\movies.py", line 18, in <module>
    import cv2
ImportError: numpy.core.multiarray failed to import

**Comment by Teabelly** [comment]
Just an update: 

I tried 
pip uninstall numpy 
then reinstall with conda - ... 
seemed to work but a new error saying the same but for matlibplot so I did the same and not I get:

WARNING: Skipping PIL as it is not installed.
(caiman) PS C:\Users\Callu> python C:\Users\Callu\anaconda3\envs\caiman\bin\caimanmanager.py install
Traceback (most recent call last):
  File "C:\Users\Callu\anaconda3\envs\caiman\bin\caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
  File "C:\Users\Callu\anaconda3\envs\caiman\lib\site-packages\caiman\__init__.py", line 4, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "C:\Users\Callu\anaconda3\envs\caiman\lib\site-packages\caiman\base\movies.py", line 22, in <module>
    from matplotlib import animation
  File "C:\Users\Callu\anaconda3\envs\caiman\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\Callu\anaconda3\envs\caiman\lib\site-packages\matplotlib\rcsetup.py", line 24, in <module>
    from matplotlib import _api, animation, cbook
  File "C:\Users\Callu\anaconda3\envs\caiman\lib\site-packages\matplotlib\animation.py", line 34, in <module>
    from PIL import Image
  File "C:\Users\Callu\AppData\Roaming\Python\Python37\site-packages\PIL\Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\Callu\AppData\Roaming\Python\Python37\site-packages\PIL\__init__.py)
(caiman) PS C:\Users\Callu> pip uninstall PIL
>>
WARNING: Skipping PIL as it is not installed

**Comment by pgunn** [comment]
Hi,
I suspect you'll have a lot more luck if you remove your environment and make a new one, getting all the prereqs using `conda env create -n caiman -f environment.yml` -- that'll ensure you get compatible versions of all the packages.
