### ISSUE TITLE
Merging overlapping components 

### ISSUE THREAD

**Issue by jesusdpa1** [flatironinstitute/CaImAn#873]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 Linux
 2. Python version (3.x): 
 3.7
 3. Working environment (Python IDE/Jupyter Notebook/other):
Python
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 latest
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 
conda
*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

- **Copy error log below**

- **If you're not reporting an error, type your message below**

Hi, I am observing overlapping components over the same neuron. Is there a way to group all of the components into one? 

![image](https://user-images.githubusercontent.com/17010046/117324996-528c0900-ae5e-11eb-9955-fb7355f7b385.png)
![image](https://user-images.githubusercontent.com/17010046/117325165-79e2d600-ae5e-11eb-9ac6-9a6250b3bd1d.png)
![image](https://user-images.githubusercontent.com/17010046/117325209-80714d80-ae5e-11eb-9997-0ca1c61a6407.png)

**Comment by pgunn** [comment]
Are you sure they're actually the same neuron under the regions? Caiman is built with the idea that the plane of view may have different neurons differentiated in the z dimension, and part of the design is to identify when such apparent overlaps are present and to disentangle them. If you're sure it's making a mistake in this separation we can talk about how to work with that.

**Comment by j-friedrich** [comment]
Hi @jesusdpa1, you can call the method [merge_comps](https://github.com/flatironinstitute/CaImAn/blob/9b6a111f83d57d066e375ef372d61c09520eda29/caiman/source_extraction/cnmf/cnmf.py#L940) to merge components. You might have to lower the parameter `merge_thr`. If you chose a lower value already when creating the CNMFParams object you end up with less duplicates in the first place, but running a final merge operation at the end of the analysis is not that uncommon.

**Comment by jesusdpa1** [comment]
Thanks Johannes, I am trying to apply merge_comps but I am getting the following errors:

original merge_thr = 0.7

```py
data.caiman.params.merging['merge_thr'] = 0.6
data.caiman.merge_comps(data.video)
Traceback (most recent call last):
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-1ffea1aa3cc6>", line 2, in <module>
    data.caiman.merge_comps(data.video[0])
  File "/home/jesusdpa/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 952, in merge_comps
    max_merge_area=max_merge_area)
  File "/home/jesusdpa/CaImAn/caiman/source_extraction/cnmf/merging.py", line 249, in merge_components
    A_merged[:, i] = csr_matrix(computedA).T
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/scipy/sparse/lil.py", line 333, in __setitem__
    IndexMixin.__setitem__(self, key, x)
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/scipy/sparse/_index.py", line 111, in __setitem__
    raise ValueError('shape mismatch in assignment')
ValueError: shape mismatch in assignment

```

```py
data.caiman.params.merging['merge_thr'] = 0.6
Y = np.transpose(data.video[0], list(range(1, len(data.caiman.dims) + 1)) + [0])
data.caiman.merge_comps(Y)

Traceback (most recent call last):
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-1476ee4dd9ca>", line 2, in <module>
    Y = np.transpose(data.video[0], list(range(1, len(data.caiman.dims) + 1)) + [0])
  File "<__array_function__ internals>", line 6, in transpose
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 658, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array

```

**Comment by akatav** [comment]
@jesusdpa1 hello, i am just wondering if you are using the ````manually_refine_components```` method to identify these cells ? if so, can you kindly explain how you manage to get the nice cell boundaries (instead of square or round cell shapes) ?

**Comment by jesusdpa1** [comment]
Hey SK, I use: cnmf to extract the components

```py 
cnm = cnmf.CNMF(n_processes=n_processes, dview=dview, Ain=Ain, params=opts)
cnm.fit(images)

and then evaluate_components and select_components to filter the components

```py 
cnm.estimates.evaluate_components(images, cnm.params, dview=dview)
cnm.estimates.select_components(use_object=True)

Then I have the following costume code to plot the data using napari

```py
def vis_neurons(data):
    """
    :param data: reload cnmf file (*.hdf5)
    :return:
    """
    contour_list = cm.utils.visualization.get_contours(data.caiman.estimates.A, data.caiman.estimates.dims)
    color_map = napari.utils.colormaps.label_colormap(num_colors=len(contour_list) + 1, seed=0.5)
    viewer = napari.view_image(data.max_intensity_filter.T)
    for i, contour in enumerate(contour_list):
        contour_plot = clean_nan(contour['coordinates'])
        viewer.add_shapes(contour_plot,
                          shape_type='polygon',
                          edge_width=2, name=f'C{i}',
                          edge_color=color_map.colors[i+1],
                          face_color=color_map.colors[i+1])

Let me know if this answers your question,

**Comment by akatav** [comment]
@jesusdpa1 thank you :) i use the fit() and evaluate_components(). I have not used the select_components() thusfar (i guess it selects the accepted components?)
I have not used napari so far for the visualization. It looks like a really nice tool for visualization. Thank you!

**Comment by jesusdpa1** [comment]
Hi @pgunn @j-friedrich, any ideas on why I am getting the following error when changing the merge threshold from the original 0.7 to 0.6:

```py 
data.caiman.params.merging['merge_thr'] = 0.6
data.caiman.merge_comps(data.video)
Traceback (most recent call last):
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-22-1ffea1aa3cc6>", line 2, in <module>
    data.caiman.merge_comps(data.video[0])
  File "/home/jesusdpa/CaImAn/caiman/source_extraction/cnmf/cnmf.py", line 952, in merge_comps
    max_merge_area=max_merge_area)
  File "/home/jesusdpa/CaImAn/caiman/source_extraction/cnmf/merging.py", line 249, in merge_components
    A_merged[:, i] = csr_matrix(computedA).T
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/scipy/sparse/lil.py", line 333, in __setitem__
    IndexMixin.__setitem__(self, key, x)
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/scipy/sparse/_index.py", line 111, in __setitem__
    raise ValueError('shape mismatch in assignment')
ValueError: shape mismatch in assignment
```
```py
data.caiman.params.merging['merge_thr'] = 0.6
Y = np.transpose(data.video[0], list(range(1, len(data.caiman.dims) + 1)) + [0])
data.caiman.merge_comps(Y)

Traceback (most recent call last):
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-30-1476ee4dd9ca>", line 2, in <module>
    Y = np.transpose(data.video[0], list(range(1, len(data.caiman.dims) + 1)) + [0])
  File "<__array_function__ internals>", line 6, in transpose
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 658, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "/home/jesusdpa/anaconda3/envs/caiman/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
ValueError: axes don't match array
```

**Comment by j-friedrich** [comment]
The `Y` in `data.caiman.merge_comps(Y)` must be a (d x T) matrix where d is the number of pixels. You can convert your TXY tensor using `caiman.movie(Y).to2DPixelxTime()`
