### ISSUE TITLE
Computing background for 1-photon data

### ISSUE THREAD

**Issue by akatav** [flatironinstitute/CaImAn#893]
Hi,

I have seen the thread https://github.com/flatironinstitute/CaImAn/issues/533 to compute background and used the compute_background() to get the background. I need it to call the detrend_df_F() method to get the normalized detrended fluoro traces for my 1 photon data. The cnm.estimates.F_dff is None in my case. 

However, I get the following error: 

```
/home/anaconda3/lib/python3.7/site-packages/caiman/source_extraction/cnmf/utilities.py:54: RuntimeWarning: divide by zero encountered in floor_divide
  dims_ds = tuple(1 + (np.array(dims) - 1) // sub)
/home/anaconda3/lib/python3.7/site-packages/caiman/source_extraction/cnmf/utilities.py:64: RuntimeWarning: divide by zero encountered in long_scalars
  ind = np.concatenate([tmp] * (dims[1] // sub + 1))[:D] + \
/home//anaconda3/lib/python3.7/site-packages/caiman/source_extraction/cnmf/utilities.py:65: RuntimeWarning: divide by zero encountered in floor_divide
  np.arange(D) // (dims[0] * sub) * ((dims[0] - 1) // sub + 1)
/home/anaconda3/lib/python3.7/site-packages/caiman/source_extraction/cnmf/utilities.py:65: RuntimeWarning: divide by zero encountered in long_scalars
  np.arange(D) // (dims[0] * sub) * ((dims[0] - 1) // sub + 1)
Traceback (most recent call last):
  File "/home//howmanyspatialcomponentsaftermincorr/howmanyspatialcomponents_1_old.py", line 44, in <module>
    B=compute_background(self, Yr)
  File "/home/howmanyspatialcomponentsaftermincorr/howmanyspatialcomponents_1_old.py", line 28, in compute_background
    ds_mat =cnmf.utilities.decimation_matrix((480,752), ssub_B)
  File "/home//anaconda3/lib/python3.7/site-packages/caiman/source_extraction/cnmf/utilities.py", line 65, in decimation_matrix
    np.arange(D) // (dims[0] * sub) * ((dims[0] - 1) // sub + 1)
ValueError: operands could not be broadcast together with shapes (0,) (360960,) 

```

I am hoping the params ```self``` in compute_background() means the cnm.estimates object. ```Yr``` is the 3d data matrix (returned after loading the .mmap files using load_memmap())

It'll be helpful to know what is wrong here.

**Comment by j-friedrich** [comment]
See issue #424 for a discussion on DF/F for 1p data
