### ISSUE TITLE
index -900 is out of bounds for axis 0 with size 100

### ISSUE THREAD

**Issue by MarziyehPourmousavi** [flatironinstitute/CaImAn#919]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): 
 
 2. Python version (3.x): 
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): 

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

Traceback (most recent call last):

  File "C:\Users\TANDIS\caiman_data\demos\general\demo_pipeline.py", line 276, in <module>
    main()

  File "C:\Users\TANDIS\caiman_data\demos\general\demo_pipeline.py", line 208, in main
    Cns = local_correlations_movie_offline(mc.mmap_file[0],

  File "c:\users\tandis\caiman\caiman\summary_images.py", line 773, in local_correlations_movie_offline
    parallel_result = dview.map_async(local_correlations_movie_parallel, params).get(4294967)

  File "C:\Users\TANDIS\anaconda3\lib\multiprocessing\pool.py", line 771, in get
    raise self._value

  File "C:\Users\TANDIS\anaconda3\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))

  File "C:\Users\TANDIS\anaconda3\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))

  File "c:\users\tandis\caiman\caiman\summary_images.py", line 784, in local_correlations_movie_parallel
    mv = cm.load(mv_name, subindices=idx, in_memory=True)

  File "c:\users\tandis\caiman\caiman\base\movies.py", line 1715, in load
    images = images[subindices]

  File "C:\Users\TANDIS\anaconda3\lib\site-packages\numpy\core\memmap.py", line 331, in __getitem__
    res = super(memmap, self).__getitem__(index)

IndexError: index -900 is out of bounds for axis 0 with size 100

**Comment by j-friedrich** [comment]
When you call `local_correlations_movie_offline` the argument `window` must be smaller or equal than the total number of frames. You seem to have 100 frames but use `window=1000`.

**Comment by pgunn** [comment]
@j-friedrich We might want to consider checking for this and raising an exception if the user tries to do that?
