### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by toparkshin** [flatironinstitute/CaImAn#960]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows): Windows 10
 
 2. Python version (3.x): 3.9 (Anaconda)
 
 3. Working environment (Python IDE/Jupyter Notebook/other): PyCharm
 
 4. Which of the demo scripts you're using for your analysis (if applicable):
 
 5. CaImAn version*: 1.9.9
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): conda

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

I've got some problem with installing caiman after the mamba installation.

error message is below..

- **Copy error log below**

>> mamba create -n caiman -c conda-forge caiman
>> conda activate caiman
>> python C:\Users\...\anaconda3\envs\caiman\bin\caimanmanager.py install

Traceback (most recent call last):
  File "C:\Users\...\anaconda3\envs\caiman\bin\caimanmanager.py", line 16, in <module>
    from caiman.paths import caiman_datadir
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\caiman\__init__.py", line 4, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\caiman\base\movies.py", line 57, in <module>
    from ..utils import visualization
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\caiman\utils\visualization.py", line 33, in <module>
    import holoviews as hv
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\holoviews\__init__.py", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\holoviews\annotators.py", line 10, in <module>
    from panel.pane import PaneBase
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\panel\__init__.py", line 1, in <module>
    from . import layout # noqa
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\panel\layout\__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\panel\layout\accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\panel\layout\base.py", line 11, in <module>
    from ..io.model import hold
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\panel\io\__init__.py", line 9, in <module>
    from ..config import config
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\panel\config.py", line 21, in <module>
    from .io.notebook import load_notebook
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\panel\io\notebook.py", line 39, in <module>
    from .resources import Bundle, Resources, _env, bundle_resources
  File "C:\Users\...\anaconda3\envs\caiman\lib\site-packages\panel\io\resources.py", line 24, in <module>
    from jinja2 import Environment, Markup, FileSystemLoader
ImportError: cannot import name 'Markup' from 'jinja2' (C:\Users\...\anaconda3\envs\caiman\lib\site-packages\jinja2\__init__.py)

**Comment by NataliaFavila** [comment]
Hello,

you can solve this by installing jinja2 version 3.0.3 inside the environment

conda install -c conda-forge jinja2=3.0.3

**Comment by toparkshin** [comment]
> Hello,
> 
> you can solve this by installing jinja2 version 3.0.3 inside the environment
> 
> conda install -c conda-forge jinja2=3.0.3

This solved the problem! Thank you so much for your kind reply.
