### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by bendichter** [flatironinstitute/CaImAn#961]
import error caused by panel 0.12.6, which is the conda default. This issue was fixed 3 days ago with the release of 0.12.7, which is available on pypi

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 23>()
     20 except NameError:
     21     pass
---> 23 import caiman as cm
     24 from caiman.motion_correction import MotionCorrect
     25 from caiman.source_extraction.cnmf import cnmf as cnmf

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/caiman/__init__.py:4, in <module>
      1 #!/usr/bin/env python
      3 import pkg_resources
----> 4 from .base.movies import movie, load, load_movie_chain
      5 from .base.timeseries import concatenate
      6 from .cluster import start_server, stop_server

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/caiman/base/movies.py:62, in <module>
     59 from .traces import trace
     61 from ..mmapping import load_memmap
---> 62 from ..utils import visualization
     63 from .. import summary_images as si
     64 from ..motion_correction import apply_shift_online, motion_correct_online

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/caiman/utils/visualization.py:33, in <module>
     31 from typing import Dict
     32 from warnings import warn
---> 33 import holoviews as hv
     34 import functools as fct
     36 from ..base.rois import com

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/holoviews/__init__.py:12, in <module>
      8 __version__ = str(param.version.Version(fpath=__file__, archive_commit="$Format:%h$",
      9                                         reponame="holoviews"))
     11 from . import util                                       # noqa (API import)
---> 12 from .annotators import annotate                         # noqa (API import)
     13 from .core import archive, config                        # noqa (API import)
     14 from .core.boundingregion import BoundingBox             # noqa (API import)

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/holoviews/annotators.py:10, in <module>
      6 from inspect import getmro
      8 import param
---> 10 from panel.pane import PaneBase
     11 from panel.layout import Row, Tabs
     12 from panel.util import param_name

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/__init__.py:1, in <module>
----> 1 from . import layout # noqa
      2 from . import links # noqa
      3 from . import pane # noqa

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/layout/__init__.py:1, in <module>
----> 1 from .accordion import Accordion # noqa
      2 from .base import Column, ListLike, ListPanel, Panel, Row, WidgetBox # noqa
      3 from .card import Card # noqa

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/layout/accordion.py:5, in <module>
      1 import param
      3 from bokeh.models import Column as BkColumn, CustomJS
----> 5 from .base import NamedListPanel
      6 from .card import Card
      9 class Accordion(NamedListPanel):

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/layout/base.py:11, in <module>
      7 import param
      9 from bokeh.models import Column as BkColumn, Row as BkRow
---> 11 from ..io.model import hold
     12 from ..io.state import state
     13 from ..reactive import Reactive

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/io/__init__.py:9, in <module>
      6 import logging
      7 import sys
----> 9 from ..config import config
     11 from .callbacks import PeriodicCallback # noqa
     12 from .embed import embed_state # noqa

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/config.py:21, in <module>
     15 import param
     17 from pyviz_comms import (
     18     JupyterCommManager as _JupyterCommManager, extension as _pyviz_extension
     19 )
---> 21 from .io.notebook import load_notebook
     22 from .io.state import state
     24 __version__ = str(param.version.Version(
     25     fpath=__file__, archive_commit="$Format:%h$", reponame="panel"))

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/io/notebook.py:39, in <module>
     37 from .embed import embed_state
     38 from .model import add_to_doc, diff
---> 39 from .resources import Bundle, Resources, _env, bundle_resources
     40 from .server import _server_url, _origin_url, get_server
     41 from .state import state

File ~/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/io/resources.py:24, in <module>
     22 from bokeh.resources import Resources as BkResources
     23 from bokeh.settings import settings as _settings
---> 24 from jinja2 import Environment, Markup, FileSystemLoader
     26 from ..util import url_path
     27 from .state import state

ImportError: cannot import name 'Markup' from 'jinja2' (/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/jinja2/__init__.py)
```

until conda updates the default, I don't think the current install instructions will work.You'll need to also

```bash
pip install -U panel
```

**Comment by pgunn** [comment]
Do you mind checking to see if panel 0.12.1 has the issue? Or I wonder if pinning an older jinja2 would do the job.

**Comment by pgunn** [comment]
It looks like jinja2 had 3.0.3 release 12 days ago; I wonder if that version has inadequate pinning.

**Comment by pgunn** [comment]
Can you get me the output of `conda list` from your caiman environment?

**Comment by bendichter** [comment]
```
# packages in environment at /Users/bendichter/opt/miniconda3/envs/caiman:
#
# Name                    Version                   Build  Channel
abseil-cpp                20210324.2           he49afe7_0    conda-forge
absl-py                   1.0.0              pyhd8ed1ab_0    conda-forge
aiohttp                   3.8.1            py39h89e85a6_0    conda-forge
aiosignal                 1.2.0              pyhd8ed1ab_0    conda-forge
aom                       3.3.0                h96cf925_1    conda-forge
appnope                   0.1.2            py39h6e9494a_2    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39h89e85a6_1    conda-forge
asttokens                 2.0.5              pyhd8ed1ab_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             4.0.2              pyhd8ed1ab_0    conda-forge
attrs                     21.4.0             pyhd8ed1ab_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.1                pyhd3eb1b0_0  
backports.functools_lru_cache 1.6.4              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.10.0             pyha770c72_0    conda-forge
bleach                    4.1.0              pyhd8ed1ab_0    conda-forge
blinker                   1.4                        py_1    conda-forge
blosc                     1.21.0               he49afe7_0    conda-forge
bokeh                     2.4.2            py39h6e9494a_0    conda-forge
brotli                    1.0.9                h0d85af4_6    conda-forge
brotli-bin                1.0.9                h0d85af4_6    conda-forge
brotlipy                  0.7.0           py39h89e85a6_1003    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.18.1               h0d85af4_0    conda-forge
c-blosc2                  2.0.4                ha1a4663_1    conda-forge
ca-certificates           2022.3.29            hecd8cb5_0  
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
caiman                    1.9.8            py39hbd61c47_0    conda-forge
cairo                     1.16.0            he43a7df_1008    conda-forge
certifi                   2021.10.8        py39h6e9494a_2    conda-forge
cffi                      1.15.0           py39he338e87_0    conda-forge
cfitsio                   4.1.0                h2c97ad1_0    conda-forge
charls                    2.3.4                he49afe7_0    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.1            py39h6e9494a_1    conda-forge
cloudpickle               2.0.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.4              pyh9f0ad1d_0    conda-forge
colorcet                  3.0.0              pyhd8ed1ab_0    conda-forge
cryptography              36.0.2           py39h1644bb1_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.11.2           py39h89e85a6_1    conda-forge
dask-core                 2022.3.0           pyhd8ed1ab_0    conda-forge
dbus                      1.13.18              h18a8e69_0  
debugpy                   1.5.1            py39h9fcab8e_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
executing                 0.8.3              pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h96cf925_0    conda-forge
ffmpeg                    4.3.2                hbf27d7b_3    conda-forge
flit-core                 3.7.1              pyhd8ed1ab_0    conda-forge
fontconfig                2.13.96              h676cef8_2    conda-forge
fonttools                 4.31.2           py39h63b48b0_0    conda-forge
freetype                  2.11.0               hd8bbffd_0  
frozenlist                1.3.0            py39h89e85a6_0    conda-forge
fsspec                    2022.2.0           pyhd8ed1ab_0    conda-forge
future                    0.18.2           py39h6e9494a_4    conda-forge
gast                      0.3.3                      py_0    conda-forge
gettext                   0.21.0               h7535e17_0  
giflib                    5.2.1                hbcb3906_2    conda-forge
glib                      2.70.2               hcf210ce_4    conda-forge
glib-tools                2.70.2               hcf210ce_4    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
gnutls                    3.6.15               hed9c0bf_0  
google-auth               1.35.0             pyh6c4a22f_0    conda-forge
google-auth-oauthlib      0.4.6              pyhd8ed1ab_0    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
graphite2                 1.3.14               h38d11af_0  
grpc-cpp                  1.37.1               h69eed7d_3    conda-forge
grpcio                    1.37.1           py39hb974310_0    conda-forge
h5py                      2.10.0          nompi_py39h1bb8402_106    conda-forge
harfbuzz                  2.9.1                h159f659_1    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
hdmf                      2.2.0              pyh9f0ad1d_0    conda-forge
holoviews                 1.14.8             pyhd8ed1ab_0    conda-forge
icu                       68.2                 he49afe7_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
imagecodecs               2022.2.22        py39ha3729fb_1    conda-forge
imageio                   2.16.1             pyhcf75d05_0    conda-forge
importlib-metadata        4.11.3           py39h6e9494a_1    conda-forge
importlib_resources       5.6.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.11.0           py39h71a6800_0    conda-forge
ipyparallel               8.2.0              pyhd8ed1ab_0    conda-forge
ipython                   8.2.0            py39h6e9494a_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.7.0              pyhd8ed1ab_0    conda-forge
jasper                    1.900.1           h636a363_1006    conda-forge
jbig                      2.1               h0d85af4_2003    conda-forge
jedi                      0.18.1           py39h6e9494a_0    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
joblib                    1.1.0              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   h0d85af4_0    conda-forge
jsonschema                4.4.0              pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0            py39h6e9494a_7    conda-forge
jupyter_client            7.2.1              pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.3              pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2            py39h6e9494a_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_widgets        1.1.0              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h35c211d_2    conda-forge
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.4.2            py39h7248d28_0    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lame                      3.100             h35c211d_1001    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libaec                    1.0.6                he49afe7_0    conda-forge
libavif                   0.9.3                h5eb16cf_1    conda-forge
libblas                   3.9.0           13_osx64_openblas    conda-forge
libbrotlicommon           1.0.9                h0d85af4_6    conda-forge
libbrotlidec              1.0.9                h0d85af4_6    conda-forge
libbrotlienc              1.0.9                h0d85af4_6    conda-forge
libcblas                  3.9.0           13_osx64_openblas    conda-forge
libclang                  11.1.0          default_he082bbe_1    conda-forge
libcurl                   7.82.0               h9f20792_0    conda-forge
libcxx                    13.0.1               hc203e6f_0    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20210910         hca72f7f_0  
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.4.2                h0d85af4_5    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_23    conda-forge
libgfortran5              9.3.0               h6c81a4c_23    conda-forge
libglib                   2.70.2               hf1fb8c0_4    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libidn2                   2.3.2                h0d85af4_0    conda-forge
liblapack                 3.9.0           13_osx64_openblas    conda-forge
liblapacke                3.9.0           13_osx64_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_3    conda-forge
libnghttp2                1.47.0               h942079c_0    conda-forge
libopenblas               0.3.18          openmp_h3351f45_0    conda-forge
libopencv                 4.5.2            py39h49f8dfa_0    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     13.5                 hea3049e_1    conda-forge
libprotobuf               3.15.8               hcf210ce_1    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libssh2                   1.10.0               h52ee1ee_2    conda-forge
libtasn1                  4.18.0               h0d85af4_0    conda-forge
libtiff                   4.3.0                h17f2ce3_3    conda-forge
libunistring              0.9.10               h0d85af4_0    conda-forge
libwebp                   1.2.2                h28dabe5_0    conda-forge
libwebp-base              1.2.2                h0d85af4_1    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.9.12               h93ec3fd_0    conda-forge
libzlib                   1.2.11            h6c3fc93_1014    conda-forge
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               13.0.1               hcb1a161_1    conda-forge
locket                    0.2.1            py39hecd8cb5_2  
lz4-c                     1.9.3                he49afe7_1    conda-forge
markdown                  3.3.6              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py39h63b48b0_1    conda-forge
matplotlib                3.5.1            py39h6e9494a_0    conda-forge
matplotlib-base           3.5.1            py39hb07454d_0    conda-forge
matplotlib-inline         0.1.3              pyhd8ed1ab_0    conda-forge
mistune                   0.8.4           py39h89e85a6_1005    conda-forge
multidict                 6.0.2            py39h89e85a6_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
mypy                      0.942            py39h63b48b0_0    conda-forge
mypy_extensions           0.4.3            py39h6e9494a_4    conda-forge
mysql-common              8.0.28               hab7e275_2    conda-forge
mysql-libs                8.0.28               h2a44bf5_2    conda-forge
nbclient                  0.5.13             pyhd8ed1ab_0    conda-forge
nbconvert                 6.4.5            py39h6e9494a_0    conda-forge
nbformat                  5.2.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.3                  he49afe7_0    conda-forge
nest-asyncio              1.5.4              pyhd8ed1ab_0    conda-forge
nettle                    3.7.3                h230ac6f_1  
networkx                  2.7.1              pyhd8ed1ab_1    conda-forge
nose                      1.3.7                   py_1006    conda-forge
notebook                  6.4.10             pyha770c72_0    conda-forge
nspr                      4.33                 he9d5cce_0  
nss                       3.76                 hfce436b_0    conda-forge
numpy                     1.22.3           py39hf56e92f_0    conda-forge
oauthlib                  3.2.0              pyhd8ed1ab_0    conda-forge
opencv                    4.5.2            py39h6e9494a_0    conda-forge
openh264                  2.1.1                hfd3ada9_0    conda-forge
openjpeg                  2.4.0                h6e7aa92_1    conda-forge
openssl                   1.1.1n               h6c3fc93_0    conda-forge
opt_einsum                3.3.0              pyhd8ed1ab_1    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pandas                    1.4.1            py39h4d6be9b_0    conda-forge
pandoc                    2.17.1.1             h694c41f_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
panel                     0.12.6             pyhd8ed1ab_0    conda-forge
param                     1.12.0             pyh6c4a22f_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 he49afe7_0    conda-forge
peakutils                 1.3.3                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5           py39hde42818_1002    conda-forge
pillow                    9.0.1            py39hd2c7aa1_2    conda-forge
pims                      0.5                pyh9f0ad1d_1    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
prometheus_client         0.13.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.27             pyha770c72_0    conda-forge
prompt_toolkit            3.0.27               hd8ed1ab_0    conda-forge
protobuf                  3.15.8           py39h9fcab8e_0    conda-forge
psutil                    5.9.0            py39h89e85a6_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
py-opencv                 4.5.2            py39h71a6800_0    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyct                      0.4.6                      py_0    conda-forge
pyct-core                 0.4.6                      py_0    conda-forge
pygments                  2.11.2             pyhd8ed1ab_0    conda-forge
pyjwt                     2.3.0              pyhd8ed1ab_1    conda-forge
pynwb                     1.4.0            py39h6e9494a_1    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39h6e9494a_8    conda-forge
pyqt-impl                 5.12.3           py39he44290a_8    conda-forge
pyqt5-sip                 4.19.18          py39h15fb055_8    conda-forge
pyqtchart                 5.12             py39he44290a_8    conda-forge
pyqtgraph                 0.12.4             pyhd8ed1ab_0    conda-forge
pyqtwebengine             5.12.1           py39he44290a_8    conda-forge
pyrsistent                0.18.1           py39h89e85a6_0    conda-forge
pysocks                   1.7.1            py39h6e9494a_4    conda-forge
python                    3.9.12          h8b4d769_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-flatbuffers        1.12               pyhd8ed1ab_1    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2022.1             pyhd8ed1ab_0    conda-forge
pyu2f                     0.1.5              pyhd8ed1ab_0    conda-forge
pyviz_comms               2.2.0              pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py39h86b5767_0    conda-forge
pyyaml                    6.0              py39h89e85a6_3    conda-forge
pyzmq                     22.3.0           py39h7fec2f1_1    conda-forge
qt                        5.12.9               h126340a_4    conda-forge
qtconsole                 5.3.0              pyhd8ed1ab_0    conda-forge
qtconsole-base            5.3.0              pyhd8ed1ab_0    conda-forge
qtpy                      2.0.1              pyhd8ed1ab_0    conda-forge
re2                       2021.08.01           he49afe7_0    conda-forge
readline                  8.1.2                hca72f7f_1  
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
requests-oauthlib         1.3.1              pyhd8ed1ab_0    conda-forge
rsa                       4.8                pyhd8ed1ab_0    conda-forge
ruamel.yaml               0.17.21          py39h89e85a6_0    conda-forge
ruamel.yaml.clib          0.2.6            py39h89e85a6_0    conda-forge
scikit-image              0.19.2           py39h4d6be9b_0    conda-forge
scikit-learn              1.0.2            py39hd4eea88_0    conda-forge
scipy                     1.8.0            py39h056f1c0_1    conda-forge
send2trash                1.8.0              pyhd8ed1ab_0    conda-forge
setuptools                61.2.0           py39h6e9494a_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
slicerator                1.0.0                      py_0    conda-forge
snappy                    1.1.8                hb1e8313_3    conda-forge
soupsieve                 2.3.1              pyhd8ed1ab_0    conda-forge
sqlite                    3.38.2               h707629a_0  
stack_data                0.2.0              pyhd8ed1ab_0    conda-forge
tensorboard               2.4.1              pyhd8ed1ab_1    conda-forge
tensorboard-plugin-wit    1.8.1              pyhd8ed1ab_0    conda-forge
tensorflow                2.4.1            py39h6e9494a_0    conda-forge
tensorflow-base           2.4.1            py39h9e0eb93_0    conda-forge
tensorflow-estimator      2.4.1              pyheb71bc4_0  
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.13.3           py39h6e9494a_0    conda-forge
testpath                  0.6.0              pyhd8ed1ab_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2022.3.25          pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5dbffcc_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.11.2             pyhd8ed1ab_0    conda-forge
tornado                   6.1              py39h89e85a6_2    conda-forge
tqdm                      4.63.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing-extensions         4.1.1                hd8ed1ab_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
unicodedata2              14.0.0           py39h89e85a6_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  2.0.3              pyhd8ed1ab_1    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
widgetsnbextension        3.6.0            py39h6e9494a_0    conda-forge
wrapt                     1.14.0           py39h63b48b0_0    conda-forge
x264                      1!161.3030           h0d85af4_1    conda-forge
xorg-libxau               1.0.9                h35c211d_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                h0d85af4_2    conda-forge
yarl                      1.7.2            py39h89e85a6_1    conda-forge
z5py                      2.0.15           py39h74502c3_0    conda-forge
zeromq                    4.3.4                he49afe7_1    conda-forge
zfp                       0.5.5                h4a89273_8    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h6c3fc93_1014    conda-forge
zstd                      1.5.2                h582d3a0_0    conda-forge
```

```python
>>> import caiman
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/caiman/__init__.py", line 4, in <module>
    from .base.movies import movie, load, load_movie_chain
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/caiman/base/movies.py", line 57, in <module>
    from ..utils import visualization
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/caiman/utils/visualization.py", line 33, in <module>
    import holoviews as hv
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/holoviews/__init__.py", line 12, in <module>
    from .annotators import annotate                         # noqa (API import)
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/holoviews/annotators.py", line 10, in <module>
    from panel.pane import PaneBase
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/__init__.py", line 1, in <module>
    from . import layout # noqa
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/layout/__init__.py", line 1, in <module>
    from .accordion import Accordion # noqa
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/layout/accordion.py", line 5, in <module>
    from .base import NamedListPanel
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/layout/base.py", line 11, in <module>
    from ..io.model import hold
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/io/__init__.py", line 9, in <module>
    from ..config import config
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/config.py", line 21, in <module>
    from .io.notebook import load_notebook
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/io/notebook.py", line 39, in <module>
    from .resources import Bundle, Resources, _env, bundle_resources
  File "/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/panel/io/resources.py", line 24, in <module>
    from jinja2 import Environment, Markup, FileSystemLoader
ImportError: cannot import name 'Markup' from 'jinja2' (/Users/bendichter/opt/miniconda3/envs/caiman/lib/python3.9/site-packages/jinja2/__init__.py)
```

**Comment by pgunn** [comment]
Looks like 0.12.7 just made it onto conda-forge and a fresh-made environment gets me that.

**Comment by bendichter** [comment]
same result. Why not just put a version constraint on it? 

`panel>-0.12.7`

**Comment by pgunn** [comment]
I could do that, but it would only impact the environment.yml install route; I'd need to cut a new release to get people doing a pure package install covered (and it'd still mean not understanding whatever's causing this behaviour).

I assume that `conda search -c conda-forge panel`
Shows 0.12.7 for you?

I'm asking the conda-forge people if they have any ideas what's going on.

**Comment by pgunn** [comment]
It's possible that just doing that search would force the repo index to update and change the package resolution.

**Comment by EricThomson** [comment]
Is this now resolved @bendichter ?  (I'm cleaning out old issues :) )
