### ISSUE TITLE
Unit tests fail to run due to problem with nose

### ISSUE THREAD

**Issue by GBarnum** [flatironinstitute/CaImAn#972]
For better support, please use the template below to submit your issue. When your issue gets resolved please remember to close it.

Sometimes errors while running CNMF occur during parallel processing which prevents the log to provide a meaningful error message. Please reproduce your error with setting `dview=None`.

If you need to upgrade CaImAn follow the instructions given in the [documentation](https://caiman.readthedocs.io/en/master/Installation.html#upgrading).

- **Tell us a bit about your setup**: 
 1. Operating system (Linux/macOS/Windows):  Linux (Ubuntu)
 
 2. Python version (3.x): 3.10
 
 3. Working environment (Python IDE/Jupyter Notebook/other):
 
 4. Which of the demo scripts you're using for your analysis (if applicable): N/A
 
 5. CaImAn version*: 
 
 6. CaImAn installation process (`pip install .`/`pip install -e .`/conda): .`/pip install -e`

*You can get the CaImAn version by creating a `params` object and then typing `params.data['caiman_version']`. If the field doesn't exist, type N/A and consider upgrading)

- **Describe the issue that you are experiencing**

`python3 caimanmanager.py test` fails to run tests, likely because the unit testing framework `nose` is no longer supported in more recent versions of python. See this issue on the nose repo: https://github.com/nose-devs/nose/issues/1099

- **Copy error log below**

```
$ python3 caimanmanager.py test
runcmd[nosetests --verbose --traverse-namespace caiman]
Traceback (most recent call last):
  File "/home/toor/miniconda3/envs/caiman_test/bin/nosetests", line 8, in <module>
    sys.exit(run_exit())
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/core.py", line 118, in __init__
    unittest.TestProgram.__init__(
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/core.py", line 179, in parseArgs
    self.createTests()
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/core.py", line 193, in createTests
    self.test = self.testLoader.loadTestsFromNames(self.testNames)
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/loader.py", line 481, in loadTestsFromNames
    return unittest.TestLoader.loadTestsFromNames(self, names, module)
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/unittest/loader.py", line 220, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/unittest/loader.py", line 220, in <listcomp>
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/loader.py", line 354, in loadTestsFromModule
    tests.extend(self.loadTestsFromDir(module_path))
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/loader.py", line 191, in loadTestsFromDir
    yield self.loadTestsFromName(
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/loader.py", line 431, in loadTestsFromName
    return self.loadTestsFromModule(
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/loader.py", line 359, in loadTestsFromModule
    return self.suiteClass(ContextList(tests, context=module))
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/suite.py", line 428, in __call__
    return self.makeSuite(tests, context, **kw)
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/suite.py", line 475, in makeSuite
    suite = self.suiteClass(
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/suite.py", line 159, in __init__
    super(ContextSuite, self).__init__(tests)
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/suite.py", line 53, in __init__
    super(LazySuite, self).__init__()
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/unittest/suite.py", line 22, in __init__
    self._tests = []
  File "/home/toor/miniconda3/envs/caiman_test/lib/python3.10/site-packages/nose/suite.py", line 106, in _set_tests
    if isinstance(tests, collections.Callable) and not is_suite:
AttributeError: module 'collections' has no attribute 'Callable'
Error in runcmd
STDOUT: None
STDERR: None

```

- **If you're not reporting an error, type your message below**

**Comment by pgunn** [comment]
Thanks for letting me know; I'll have to decide whether to move to pytest, nose2, or something else.

**Comment by pgunn** [comment]
Do you mind telling me what version of nose you ended up with?
It's still passing nose tests locally with python 3.10.4 (I ended up with nose 1.3.7). It's possible this is something that was patched in conda-forge.

**Comment by pgunn** [comment]
I looked into it more deeply and I think this is something we *could* leave be for awhile, as it only affects installs not done through conda (and conda is the expected install route for people contributing code). But it would be nice for people installing some other way to run the test suite (maybe even more important for them given they're off the beaten path).

I'll likely decide whether to port the test suite to nose2 or pytest and port in sometime in the next few weeks.

**Comment by EricThomson** [comment]
Closing because it seems resolved. @GBarnum please reopen if I'm mistaken.
